### ISSUE TITLE
Suggestion: Show stages in test summary

### ISSUE THREAD

**Issue by ChristianSauer** [taverntesting/tavern#106]
Currently, only top level tests are shown when the results are printed, but it would be great if we could see the stages, too.

**Comment by michaelboulton** [comment]
I've improved the docstring of the tests a bit in `0.10.1` for use with pytest-pspec, which automatically prints the docstrings of tests. It should work if you just `pip install pytest-pspec` then run your tests with `py.test --pspec .....`

This seemed like a better option than just making the names of the tests contain the name of every stage, which could make them very long.

**Comment by michaelboulton** [comment]
Closing as this should be fixed.
