### ISSUE TITLE
Using it with python 2.7?

### ISSUE THREAD

**Issue by sankalp58** [taverntesting/tavern#11]
Earlier my most of work of api design is done in django and python 2.7.Can I use this for API testing in python 2.7 or  will work in function with python 3 only ?

**Comment by benhowes** [comment]
Hi @sankalp58, I've started working on support for this, however it looks like there's actually a fair few parts which will need alteration. The WIP PR is here: https://github.com/taverntesting/tavern/pull/13. I've done enough to get the tests to run at all, but many are failing on python 3 specific code. If you're able to chip in with the backport that would be really helpful!

**Comment by sankalp58** [comment]
I will surely help if I could.I am closing this as #13 already is thread.

**Comment by benhowes** [comment]
Python 2.7 is available on pip now :)
