### ISSUE TITLE
requirements.txt  update

### ISSUE THREAD

**Issue by stephen346** [taverntesting/tavern#12]
Hello,

In the list of the requirements can you add  pytest-runner

**Comment by michaelboulton** [comment]
Although Tavern can use pytest, it's not strictly a requirement so I don't especially want to add it.

What's the issue you're running in to with it not having pytest-runner as a dependency? Can you not just install it alongside tavern?

**Comment by stephen346** [comment]
Michael,

I was installing this on a windows 7 pc with python 3.6x. 

The install of python was a clean install of python.

When I ran the pip install tavern . I was getting a lot of errors on the install.

I looked on git and found the requirements doc, installed every thing in this doc and still had issues.

It was not until I installed pytest that the issues were resolved.

S\tephen

**Comment by michaelboulton** [comment]
I haven't added it to the requirements for the main package, but in version `0.2.1` you should now be able to do `pip install tavern[pytest]` which will install pytest alongside tavern.
