### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by IaroslavR** [taverntesting/tavern#127]
In [example](https://taverntesting.github.io/examples) "Tavern tests in deploy scripts"
```
from tavern.core import run

success = run("test_server.tavern.yaml", {})

if not success:
    print("Error running tests")
```
I got `TypeError: run() takes exactly 4 arguments (2 given)`. Currently run call looks like:
```
    run(**{
        'tavern_global_cfg': None,
        'in_file': '<path_to_yaml>,
        'tavern_http_backend': 'requests',
        'tavern_mqtt_backend': 'paho-mqtt'
    })
```

**Comment by michaelboulton** [comment]
I realised that I updated the function without changing the documentation a couple of times, the `run()` function has always been a bit annoying to account for and it will probably be changed to just run a Pytest instance in the background in the near future (though it should still maintain backwards compatibility - see https://github.com/taverntesting/tavern/pull/130 )

**Comment by IaroslavR** [comment]
@michaelboulton  
>it will probably be changed to just run a Pytest instance
I use `run()` in my [locust](https://docs.locust.io/en/latest/what-is-locust.html) load tests with tavern yaml scenarios which used in pytests too. And I think I'm not the only one who uses tavern not only in `pytest`

**Comment by michaelboulton** [comment]
The plan was to just run it in the background with `pytest.main()` - if the startup time is going to be a huge issue when running it in the background then I could add an option to directly call `run_test()` like before, but it's not going to have a lot of the new functionality that is being added (marking tests etc). I'm guessing you don't need that if it's being used for load testing though?

**Comment by michaelboulton** [comment]
I've done some local testing and had a chat with people and I think we will just make `run()` always call a `pytest.main()` instance in the background. The behaviour should be the same, but it might be a bit slower due to collection.

We don't want to have to support 2 different entry points that behave differently, and have some of the documentation just not apply depending on how the library is being used.

**Comment by michaelboulton** [comment]
I've updated the documentation (and the code) to make it so that it should behave like it used to to maintain backwards compatibility. It should behave the same but print out some Pytest information - this can be disabled by telling Pytest to be quiet like this:
```python
run("test_file.tavern.yaml", pytest_args=["-qq"])
```

**Comment by IaroslavR** [comment]
@michaelboulton I understand your reasons. Anyway we write on the python :) and I do not think that I will have great difficulty using  your library the way that I need. Thank you for writing `tavern` for us
