### ISSUE TITLE
Can we parse response ??

### ISSUE THREAD

**Issue by ankajgoel** [taverntesting/tavern#131]
Hi tavern team,

Want to know if there is any easy way to parse the response returned by a test and save it, for other tests? 

e.g. From one of my test i get response as below. I want to parse this and use abc/id in a subsequent test

    {
      "key": "Success \"abc/<id>"
    }

Thanks.

**Comment by benhowes** [comment]
See the docs: https://taverntesting.github.io/documentation#saving-data-with-external-functions

You can use the `save` keyword for simple usecases, however in you case, you can write a simple python function to do the parsing and then call it with `$ext`
