### ISSUE TITLE
Breaking changes in 0.12.0?

### ISSUE THREAD

**Issue by cetanu** [taverntesting/tavern#132]
G'day,

I'm trying to understand why all of my tests are broken after updating to 0.12.0

It appears that instead of running the file passed to tavern as an argument, it is attempting to run all of my unit tests instead, but they're all 'deselected' so nothing runs at all.

Here's some relevant output:

```
$ tavern-ci --stdout test/acceptance/proxy_healthchecks.tavern.yaml
============================= test session starts ==============================
platform darwin -- Python 3.6.4, pytest-3.6.2, py-1.5.3, pluggy-0.6.0
rootdir: /Users/redacted/PycharmProjects/envoy-py-control-plane, inifile:
plugins: tavern-0.12.0, mock-1.10.0
collected 15 items / 15 deselected

=============================== warnings summary ===============================
<undetermined location>
  Module already imported so cannot be rewritten: tavern

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================== 15 deselected, 1 warnings in 0.38 seconds ===================
```

Everything works fine in 0.11.0.

What do I need to change to use the new version? I'm not doing anything special with my test setup

**Comment by cetanu** [comment]
Turns out that my files were named incorrectly and needed to be test_*.tavern.yaml

**Comment by FranciscoKloganB** [comment]
I'm having this same problem, but my files are called test_*.tavern.yaml

**Comment by benhowes** [comment]
@FranciscoKloganB: command you're using to run tavern, version and output?

**Comment by FranciscoKloganB** [comment]
##### Got the error running both:
* tavern-ci test_name_of_test.py on the folder, that files are at
* python call_overview_test.py, whose code is:

`import os
import tavern.core

base_path = os.getcwd() + "/tests/yaml_tests/calls_overview_tests"
 tavern.core.run(basepath + "/test_default.tavern.yaml")
 a few more lines of tavern.core.run for other files.
`
