### ISSUE TITLE
Check for one item in a list

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#133]
If a server returns this:

```yaml
- a
- b
- c
- d
- e
```

and I just want to make sure `e` is there and ignore the rest. This will probably just require expanding what 'strict' key checking can do

**Comment by michaelboulton** [comment]
Also I don't care how many items are in the list

**Comment by RoCCoCo13** [comment]
Hi all,
I just tested the change of this brunch with one case we have, and we are still getting the error:
`- Value mismatch in body: Length of returned list was different than expected - expected 1 items, got 7`
I can attach the rest of the logs in case is useful.
`E   - Value mismatch in body: Length of returned list was different than expected - expected 1 items, got 7 (expected["0"]["chargingStations"]["0"]["chargePoints"] = '[{'dcsCpId': 'DE:DCS:CHARGE_POINT:958e53ec-2da3-37fc-9f67-c9cf27632cfa'}]', actual["0"]["chargingStations"]["0"]["chargePoints"] = '[{'dcsCpId': 'DE:DCS:CHARGE_POINT:0a87fc17-f748-3405-b5fa-02435ad37a7c', 'incomingCpId': '18AS60POINT6', 'dynamicInfoAvailable': True, 'connectors': [{'plugType': 'IEC_62196_T_1_M_CABLE', 'administrativeState': 'INMAINTENANCE', 'chargingSpeed': 'FAST'}, {'plugType': 'IEC_62196_T_1_F_NOCABLE', 'chargingSpeed': 'UNKNOWN'}], 'isonormedID': True, 'modes': ['UNKNOWN']}, {'dcsCpId': 'DE:DCS:CHARGE_POINT:6f7eb140-ba1a-38e9-b1c7-008f956bdaf7', 'incomingCpId': '18AS60POINT5', 'administrativeState': 'INMAINTENANCE', 'dynamicInfoAvailable': True, 'connectors': [{'plugType': 'IEC_62196_T_2_COMBO', 'administrativeState': 'INMAINTENANCE', 'chargingSpeed': 'FAST'}, {'plugType': 'IEC_62196_T_3_C_F_NOCABLE', 'chargingSpeed': 'UNKNOWN'}], 'isonormedID': True, 'modes': ['LEGACY_INDUCTIVE']}, {'dcsCpId': 'DE:DCS:CHARGE_POINT:958e53ec-2da3-37fc-9f67-c9cf27632cfa', 'incomingCpId': '18AS60POINT1', 'administrativeState': 'INSERVICE', 'dynamicInfoAvailable': False, 'voltage': 240, 'powerLevel': 250, 'connectors': [{'plugType': 'DOMESTIC_F', 'administrativeState': 'INMAINTENANCE', 'phaseType': 'DC', 'chargingSpeed': 'MID_ACCELERATED'}, {'plugType': 'UNKNOWN', 'chargingSpeed': 'UNKNOWN'}, {'plugType': 'DOMESTIC_J', 'administrativeState': 'OUTOFSERVICE', 'cableAttached': 'ATTACHED', 'phaseType': 'AC_THREE_PHASES', 'chargingSpeed': 'ACCELERATED'}, {'plugType': 'DOMESTIC_E', 'administrativeState': 'INSERVICE', 'cableAttached': 'FLOATING', 'phaseType': 'AC_SINGLE', 'ampere': 2, 'powerLevel': 250, 'voltage': 240, 'chargingSpeed': 'STANDARD_SPEED', 'realEnergyValue': 3.0}], 'isonormedID': True, 'modes': ['MODE_1']}, {'dcsCpId': 'DE:DCS:CHARGE_POINT:42f13044-1bf8-3eff-a20c-a6ad2fcf6483', 'incomingCpId': '18AS60POINT2', 'administrativeState': 'OUTOFSERVICE', 'dynamicInfoAvailable': False, 'connectors': [{'plugType': 'IEC_309_2_1_PH', 'administrativeState': 'INMAINTENANCE', 'chargingSpeed': 'ACCELERATED'}, {'plugType': 'CHADEMO', 'administrativeState': 'OUTOFSERVICE', 'chargingSpeed': 'FAST'}, {'plugType': 'DOMESTIC_G', 'administrativeState': 'PLANNED', 'chargingSpeed': 'FAST'}, {'plugType': 'TESLA_SPECIFIC', 'chargingSpeed': 'UNKNOWN'}], 'isonormedID': False, 'modes': ['MODE_2']}, {'dcsCpId': 'DE:DCS:CHARGE_POINT:666a8c25-e0c7-3903-86bf-1ed49c78145e', 'incomingCpId': '18AS60POINT4', 'administrativeState': 'INMAINTENANCE', 'dynamicInfoAvailable': True, 'connectors': [{'plugType': 'IEC_62196_T_2_F_NOCABLE', 'administrativeState': 'INMAINTENANCE', 'chargingSpeed': 'FAST'}, {'plugType': 'IEC_62196_T_3_A_F', 'chargingSpeed': 'UNKNOWN'}], 'isonormedID': True, 'modes': ['MODE_4']}, {'dcsCpId': 'DE:DCS:CHARGE_POINT:062194e3-1921-3806-935b-d3715d96e612', 'incomingCpId': '18AS60POINT3', 'administrativeState': 'PLANNED', 'dynamicInfoAvailable': True, 'connectors': [{'plugType': 'IEC_62196_T_1_M_CABLE', 'administrativeState': 'PLANNED', 'chargingSpeed': 'FAST'}, {'plugType': 'IEC_62196_T_2_F_CABLE', 'chargingSpeed': 'UNKNOWN'}], 'isonormedID': True, 'modes': ['MODE_3']}, {'dcsCpId': 'DE:DCS:CHARGE_POINT:c13b06e1-c96b-3302-a0cb-8f69eeb1f56c', 'incomingCpId': '18AS60POINT7', 'dynamicInfoAvailable': True, 'connectors': [{'plugType': 'UNKNOWN', 'chargingSpeed': 'UNKNOWN'}, {'plugType': 'IEC_62196_T_1_COMBO', 'administrativeState': 'INMAINTENANCE', 'chargingSpeed': 'FAST'}], 'isonormedID': True, 'modes': ['UNKNOWN']}]')`

**Comment by StefanUPB** [comment]
Is there generally a way to check for non-exact matches? Eg, test if `abc` is **included** in a certain field. So this should pass even for `defabcdef`.

**Comment by michaelboulton** [comment]
After coming back to look at this because I want to fix it in 1.0 - despite what I said in https://github.com/taverntesting/tavern/pull/162#issuecomment-414304895 I think that in 1.0 strict key checking should allow you to do this. If the response is ` [ 1, 2, 3 ] ` then `strict` being true - the default - will match _only_ `[1, 2, 3]`. Strict being false will match

- `[1, 2, 3]`
- `[1]`
- `[2]`
- `[3]`
- `[1, 2]`
- `[2, 3]`
- `[1, 3]`

But not:

- `[3, 1]`,  `[2, 1]` - out of order
- `[2, 4]` - not present

I can't recall any issue being raised about the way to set/unset strict key matching for particular stages/tests globall/locally, so that will stay the same.

@benhowes thoughts?

**Comment by michaelboulton** [comment]
https://github.com/taverntesting/tavern/issues/495
