### ISSUE TITLE
Run tavern inside existing pytest session

### ISSUE THREAD

**Issue by kstera** [taverntesting/tavern#144]
I'd like to run tavern inside "regular" pytest scenarios so that each scenario would consist of 2 parts:

1. do some activity that affects server responses,
2. run tavern with different yaml file(s)

From user perspective this could look like this: write regular pytest scenarios and wrap running of tavern inside a fixture that just passes user tavern.yaml files (and any dynamically generated variables) as tavern arguments. 
At the moment this causes running pytest inside pytest. Could tavern be run as part of other pytest scenarios in the same session without starting a new one?

**Comment by michaelboulton** [comment]
I don't think this is possible at the moment - do you essentially just want to be able to run some Python code before running the Tavern test? If so, there is some ongoing work in this space at the moment (https://github.com/taverntesting/tavern/pull/115, https://github.com/taverntesting/tavern/pull/115#issuecomment-402486128, https://github.com/taverntesting/tavern/pull/143)

**Comment by benhowes** [comment]
@kstera closing this for now, please re-open if you can provide some clarification or if this is still relevant!
