### ISSUE TITLE
Filtering the debug logging

### ISSUE THREAD

**Issue by ade18** [taverntesting/tavern#145]
I will like to filter what is being logged into a file to only the request.py and response.py when i run a test in debugging mode.
 For instance i run a test pytest  --log-file-level=debug --log-file=logs.lo test_name and i only want to see the request and the response in the logs(output of request.py and response.py).  Where can i make this modification in the tool??

Thanks in advance

**Comment by michaelboulton** [comment]
You will need to set up the logging to filter out the files you don't care about. This is how the logging it set up in Tavern: https://github.com/taverntesting/tavern/blob/5dcc9c2f3b0c220346f620308c438d3e75b2f0cd/tests/conftest.py#L7-L12

The [Python documentation](https://docs.python.org/3.5/library/logging.config.html#logging.config.dictConfig) has information about how to filter certain modules at certain levels
