### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#146]
There should be some way to combine the coverage from running unit and integration tests to get a more accurate representation of code coverage. The instructions seem to not work because it appends tox directories to some of the tox runs for some reason: https://coverage.readthedocs.io/en/coverage-4.2/cmd.html#combining-data-files

**Comment by Birne94** [comment]
These are the commands we use to run unit and integration tests, and combining them to a single HTML report:

```sh
COVERAGE_FILE=.coverage_unit PYTHONPATH=`pwd` python -m pytest --cov api tests/api
COVERAGE_FILE=.coverage_integration PYTHONPATH=`pwd` python -m pytest --tavern-http-backend=flask --tavern-global-cfg=tests/integration/tavern.conf.yaml --cov api tests/integration
python -m coverage combine .coverage_unit .coverage_integration
python -m coverage html
```

**Comment by michaelboulton** [comment]
The issue is that because it changes directory in tox-integration.ini then all the coverage reports come out like this 
```
/home/michael/code/tavern/tavern/.tox/py35-generic/lib/python3.5/site-packages/tavern/__init__.py                       1      1     0%   1
/home/michael/code/tavern/tavern/.tox/py35-generic/lib/python3.5/site-packages/tavern/_plugins/__init__.py              0      0   100%
/home/michael/code/tavern/tavern/.tox/py35-generic/lib/python3.5/site-packages/tavern/_plugins/mqtt/__init__.py         0      0   100%
/home/michael/code/tavern/tavern/.tox/py35-generic/lib/python3.5/site-packages/tavern/_plugins/mqtt/client.py         124    102    18%   8-10, 48-133, 139-184, 195-200, 216-222, 227-234, 241-242, 245-265, 268, 271-272
/home/michael/code/tavern/tavern/.tox/py35-generic/lib/python3.5/site-packages/tavern/_plugins/mqtt/request.py         31     17    45%   24-32, 42-59, 68-72, 76
/home/michael/code/tavern/tavern/.tox/py35-generic/lib/python3.5/site-packages/tavern/_plugins/mqtt/response.py        73     59    19%   12-14, 24-40, 43-46, 55-123
```
etc.

Trying to combine them by setting the paths setting (https://coverage.readthedocs.io/en/coverage-4.2/config.html#config-paths) doesn't work either

```ini

paths = 
    tavern/
    .tox/py35-generic/lib/python3.5/site-packages/tavern/
```

**Comment by michaelboulton** [comment]
Just going back to this, it turns out the documentation is just confusing and it should actually be like this:
```ini
[paths]
tavern = 
    tavern/
    .tox/py35-generic/lib/python3.5/site-packages/tavern/
```
ie, 'tavern' not 'source'

**Comment by jykae** [comment]
@michaelboulton what was the conclusion for this? trying to get pytest-cov working with tavern

And thanks for creating such unique and great framework on top of pytest features to easily test APIs, absolutely nicely designed ❤️
