### ISSUE TITLE
Doumentation source files are git-ignored.

### ISSUE THREAD

**Issue by funkyfuture** [taverntesting/tavern#15]
the source files of the documentation [are not tracked with the vcs](https://github.com/taverntesting/tavern/blob/master/docs/source/.gitignore#L1). that makes it hard to adapt the docs to reflect changes of the software. :-/

**Comment by michaelboulton** [comment]
The documentation for the files isn't actually used at the moment, but it does remind me that it needs to be done and uploaded to RTD or something at some point.

For future reference the quickstart/example documentation is currently in this repository https://github.com/taverntesting/taverntesting.github.io

**Comment by funkyfuture** [comment]
thanks for the clarification. as a potential, non-maintaining contributor i don't find that practical. specifically the separation of code and docs in two repos. maybe the doc repo could include the code repo as a submodule? though that's not really cool either.

**Comment by michaelboulton** [comment]
The main package documentation has now been moved into the main Tavern repo, and is published to RTD.
