### ISSUE TITLE
delay_before possible bug?

### ISSUE THREAD

**Issue by cetanu** [taverntesting/tavern#159]
Got this weird thing:

    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
     - Value '2' is not unique. Previous path: '/stages/3/delay_before'. Path: '/stages/6/delay_before'.
     - Value '2' is not unique. Previous path: '/stages/3/delay_before'. Path: '/stages/9/delay_before'.: Path: '/'>

This is because I had `delay_before: 2` in two tests, in two different stages.

Why would they need to be unique? Isn't it just the number of seconds?

**Comment by michaelboulton** [comment]
This should be fixed in the latest version, the pykwalify schema was not behaving as expected

**Comment by benhowes** [comment]
@cetanu Thanks for raising this!

**Comment by cetanu** [comment]
No problem :) thanks for such a great library
