### ISSUE TITLE
Module already imported so cannot be rewritten: tavern

### ISSUE THREAD

**Issue by zurek11** [taverntesting/tavern#160]
Hello. i have this warning at the end of test. Where can be problem? Or is there some way to ignore warnings at least? Thank you.

**Comment by benhowes** [comment]
@zurek11 can't help you without more context than that? Can you provide details of how you're running your tests and perhaps a test file if it's specific to that?

**Comment by michaelboulton** [comment]
It's some kind of warning from Pytest because you're importing tavern then it's being run from inside Pytest as a plugin. It happens with pytest-cov as well (see https://github.com/pytest-dev/pytest-cov/issues/148). It can be safely ignored, I'm not sure how to suppress it though

**Comment by zurek11** [comment]
I saw that it can be changed in pytest.ini but idk where is this folder.
