### ISSUE TITLE
cannot install from other pip_index

### ISSUE THREAD

**Issue by gocarlos** [taverntesting/tavern#163]
When trying to install this package with

```bash
pip3 install -i https://devops.myURL/artifactory/api/pypi/pypi-all/simple -r requirements.txt
```
with requirements.txt
```
pytest
tavern[pytest]
```
one gets the following error: 
```
Collecting pytest (from -r requirements.txt (line 1))
  Downloading https://devops.myURL/artifactory/api/pypi/pypi-all/packages/77/64/3a76f6fbb0f392d60c5960f2b2fbad8c2b802dada87ca6d1b99c0083a929/pytest-3.6.3-py2.py3-none-any.whl (195kB)
Collecting tavern[pytest] (from -r requirements.txt (line 2))
  Downloading https://devops.myURL/artifactory/api/pypi/pypi-all/packages/83/9f/419752827e66422a144597a40f4d53b1805f6af57ee64006f547bf1f89a0/tavern-0.14.4.tar.gz (42kB)
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [Errno 99] Cannot assign requested address -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno 99] Cannot assign requested address -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_4ygw1zi/tavern/setup.py", line 87, in <module>
        "tests": TESTS_REQUIRE
      File "/home/one/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 130, in setup
        _install_setup_requires(attrs)
      File "/home/one/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 125, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/one/.local/lib/python3.5/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/one/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 773, in resolve
        replace_conflicting=replace_conflicting
      File "/home/one/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1056, in best_match
        return self.obtain(req, installer)
      File "/home/one/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1068, in obtain
        return installer(requirement)
      File "/home/one/.local/lib/python3.5/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/one/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_4ygw1zi/tavern/
```

the Installation fails as this (ci) machine has only connectivity to this registry and not to the internet..

cc @max-wittig

**Comment by benhowes** [comment]
@gocarlos it's pretty clear this relates to how you're installing tavern from a mirror rather than anything specific to tavern.  If you look at https://github.com/taverntesting/tavern/blob/master/setup.py#L59-L72, you can see all the requirements that Tavern is looking for, I don't know much about that, but perhaps setup tools can be told where to fetch packages? Or you can install them before tavern?

**Comment by benhowes** [comment]
I think you're on to something @gocarlos - sorry for closing this! It **might** be related to us using `setup_requires` rather than `install_requires` in the Tavern setup.py.

**Comment by michaelboulton** [comment]
If you look in that original error message it is giving errors about not being able to contact pypi to download the pytest runner package, which I think is the actual problem here. does it work if you do `pip install -i https://devops.myURL/artifactory/api/pypi/pypi-all/simple pytest-runner` ?

**Comment by michaelboulton** [comment]
In fact this is possibly a bug in setuptools, I've ran into other weird issues to do with test_requires/extras_require in the past

**Comment by gocarlos** [comment]
The machine we are talking about has only connectivity to this artifactory, has no internet at all... 
Though all pypi packages are mirrored on this artifactory

When i do 

pip3 install -U pytest-runner

It gets the package from the artifactory...

@michaelboulton
I’ll check what happens if i use your command

**Comment by michaelboulton** [comment]
I think the easiest thing is just for us to remove `pytest-runner` from the setup_requires, that's where the issue is and it's only every useful if you want to do `python setup.py test`. Seeing as we're just using tox and pytest to do everything it's not required any more.

**Comment by benhowes** [comment]
@gocarlos 0.17.0 changes the installer to not use the `install_requires` packages which seemed to be what was causing the issue with artifactory. Can you let us know if that solves the issue?

**Comment by michaelboulton** [comment]
Currently just having an issue with deploying it via travis https://github.com/taverntesting/tavern/issues/169

**Comment by gocarlos** [comment]
tested now with version 0.17.2, works out of the box with new pip index, 
Just needed to upgrade setuptools as we are still using debian 8... 
thanks :D
