### ISSUE TITLE
Support for a timeout parameter for requests

### ISSUE THREAD

**Issue by justinfay** [taverntesting/tavern#164]
I would like to be about to specify a timeout parameter for each of my requests, this would be useful for endpoints that must return a given timeout. https://github.com/taverntesting/tavern/blob/2ff7f97e3c705b9a935ab05aef52545a85b332cb/tavern/_plugins/rest/request.py#L64-L67 seems like a good place to slot it in with a possible default of `None`. I wouldn't mind making a PR for this if this route seems like a good idea.

**Comment by benhowes** [comment]
@justinfay I think that's a good idea! I'm not sure that we'd want to set the timeout by default, being able to set it from the test yaml should be fairly easy. @michaelboulton will be able to guide you better than me however.
