### ISSUE TITLE
Using external functions for validation

### ISSUE THREAD

**Issue by madhukar01** [taverntesting/tavern#173]
The documentation/examples do not have complete information about using external functions for validation.

- How to mark a test as failed from the external function?
For example, If I have a custom function for validating the response, how can the external function tell validation has failed.

**Comment by michaelboulton** [comment]
If you raise an exception in the external function it should mark the test as failed, and it should log what the exception was.

I'll fix the documentation for this when I get the chance, thanks for pointing this out.
