### ISSUE TITLE
Don't log "AssertationError" on non strict key matching

### ISSUE THREAD

**Issue by benhowes** [taverntesting/tavern#176]
https://github.com/taverntesting/tavern/blob/master/tavern/util/dict_util.py#L258-L292

Currently when matching headers for example, when you have non-strict matching, but you're using the logs to debug problems you see a warning level log containing:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tavern/util/dict_util.py", line 259, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'cache-contr...xt/html', ...} == {'cache-control': 'no-store'}
  Common items:
  {'cache-control': 'no-store'}
  Left contains more items:
  {'connection': 'Close',
   'content-length': '3255',
   'content-type': 'text/html',
   'pragma': 'no-cache',
   'x-powered-by': 'Zoetrope (https://zoetrope.io)'}
  Full diff:
  - {'cache-control': 'no-store',
  ?                             ^
  + {'cache-control': 'no-store'}
  ?                             ^
  -  'connection': 'Close',
  -  'content-length': '3255',
  -  'content-type': 'text/html',
  -  'pragma': 'no-cache',
  -  'x-powered-by': 'Zoetrope (https://zoetrope.io)'}
```

In the logs. I wouldn't blame anyone for thinking that's pertinent to a problem, however if you've got non strict matching, the `(tavern.util.dict_util:302) Skipping comparing missing key pragma due to strict=False` lines which follow it null it out.

This is not a functional defect of course, just that I think we can make the logs easier to debug from by not printing this as it currently it.

**Comment by benhowes** [comment]
I disagree with it being "something unexpected" - if you've got non-strict matching enabled (as you do by default), then it's entirely expected behaviour? As it is, a warning level log is something that flags it up as if it's a problem, which unless you're familiar with the source code is not something you'd know needs to be disregarded.

I really think we should change this

**Comment by michaelboulton** [comment]
I could change it to the 'debug' log level and flesh out the error message a bit to emphasise that the given message is not a hard error, but I am strongly against removing it for the reason described above

**Comment by pmneve** [comment]
I think changing it to 'debug' level with a little fleshing out of the message is a reasonable compromise.  It makes reading the log a lot easier with 'warning' or 'info' but allows checking on it using 'debug'
Make that a +1.
