### ISSUE TITLE
tavern-beta-new-traceback

### ISSUE THREAD

**Issue by cetanu** [taverntesting/tavern#179]
How do we use this option? The doco says:

> you can use the tavern-beta-new-traceback flag, either in the configuration file or on the command line

But it doesn't explain how you would do this.

I also can't find any documentation on a tavern configuration file, and didn't even know that such a thing existed

I searched the codebase and also couldn't find any instances of 'tavern-beta-new-traceback' or similar strings... So... is this even real?

**Comment by michaelboulton** [comment]
The documentation should say "in the _pytest_ configuration file", I'll fix that now. It's just used like any other pytest flag (ie, `--tavern-beta-new-traceback` on the command line or
```
tavern-beta-new-traceback = True
```
in the config file)
