### ISSUE TITLE
Access any response as a variable

### ISSUE THREAD

**Issue by jgroom33** [taverntesting/tavern#184]
The ability to store a variable for use in the next request is good. This approach is even better:

https://github.com/eykhagen/strest/blob/master/README.md#connecting-multiple-requests

**Comment by michaelboulton** [comment]
If I'm reading that correctly, you can only use values from the JSON body? Ie not the headers or Tavern's concept of the `redirect_query_params`.

It is an interesting approach, but it would also be a breaking API change (and Tavern stage names can be very long strings so even indexing them would be annoying). As it's very unlikely to ever change, I'm going to close this.
