### ISSUE TITLE
Loading environment variables from global config file

### ISSUE THREAD

**Issue by alysivji** [taverntesting/tavern#187]
This is related to #73

Right now I can load environment variables from other files if I specify it in the includes

```yaml
includes:
  - !include common.yaml
```

When I remove this entry and try to run it via pytest, environment variables do not get loaded.

`pytest --tavern-global-cfg=tests/functional-tests/common.yaml`

```console
requests.exceptions.MissingSchema: Invalid URL '{tavern.env_vars.API_URL}/movies': No schema supplied. Perhaps you meant http://{tavern.env_vars.API_URL}/movies?
```

Would really appreciate the ability to specify environment variables in global config files.

Thanks for this great project!

**Comment by michaelboulton** [comment]
Thanks for spotting that - It should now be fixed in 0.18.2 so that it will format environment variables in config files included via the command line/pytest configuration file.
