### ISSUE TITLE
[documentation] Clarify maintenance status (ie: Zoetrope Labs)

### ISSUE THREAD

**Issue by niparis** [taverntesting/tavern#196]
Observation 1: The last commit is four days ago - feels reasonably active.

Observation 2: Scrolling at the bottom of the documentation page (https://taverntesting.github.io), we can read "Developed and maintained by #Zoetrope Labs". Zoetrope Labs's website informs the reader that the company has been discontinued ("Important: Zoetrope Labs has decided to close down after 5 great years of business. The team are moving on to new adventures. This site is left up for reference only."). Conclusion of the reader: there is no active maintainer, i should not invest time in learner this library

Suggestion to clarify the documentation: 
- a section in the readme of the repo to explain the history / current maintainer
- update https://taverntesting.github.io

**Comment by michaelboulton** [comment]
Thanks for spotting that, I thought @benhowes had changed it. It's updated now/

For reference, Tavern is maintained in spare time on a best-effort basis which is why it sometimes takes a while to get back to issues.
