### ISSUE TITLE
Typo: "comparisions" vs "comparisons"

### ISSUE THREAD

**Issue by cjchand** [taverntesting/tavern#197]
First off, many thanks for creating Tavern! Can say, other than my floundering about related to #94 due to my lack of proper Py dev experience, Tavern has been a breeze to use.

I was trying to import my code to do comparisons on field values (e.g.: <, >, >=, etc) when I came across your util that already does that. But, I did notice that there's a typo in the name of one of the arguments: "comparisions" - which I suspect should be "comparisons."

Guessing no one's noticed because there's not much documentation around the coolness you have stashed away in your utils :)

Anyway, just calling it out in case others come across it.

**Comment by michaelboulton** [comment]
Thanks for spotting that, it should be fixed now.
