### ISSUE TITLE
Tavern integration issue with [tox, pytest, django]

### ISSUE THREAD

**Issue by zurek11** [taverntesting/tavern#198]
Hi. I want to run tavern integration tests on my test database created in my test django environment. Also I want to run django server before run testing. (without typing and starting server manually) Tox manage all tests. Is there some possibility to do this stuff? If not is there some solution to enhance tavern? Thank you.

PS: also I use pytest-django library.

**Comment by zurek11** [comment]
Please can you explain what exactly that function in confest.py does? And how it does? I think that wont run test server only get test server url (and what url? Without uri?)

**Comment by Birne94** [comment]
Does django provide a test-server similar to flask? Maybe a tavern plugin like [tavern-flask](https://github.com/taverntesting/tavern-flask) would work here.

**Comment by michaelboulton** [comment]
@zurek11 it uses the Django live server things (https://docs.djangoproject.com/en/2.1/topics/testing/tools/#django.test.LiveServerTestCase) which pytest-django wraps in the `live_server` fixture (https://pytest-django.readthedocs.io/en/latest/helpers.html#live-server) which Tavern then loads and uses the URL of as a format argument (https://taverntesting.github.io/documentation#usefixtures)

**Comment by zurek11** [comment]
Wow I didn't know that. Thank you very much 👍

**Comment by zurek11** [comment]
I have one issue related to this. How will I make postgres test_db creation? Django makes test_db but empty. I manually filled up that database, but when i will run tests, pytest-django wants to flush that test_db at the end or between tests because pytest-django wants to database to be isolated between tests. So i would like to create (if is not created yet) test_db before running tavern tests next i would like to fill that DB and simply use it with that live_server method with tavern (which is already working really well TY for that.). Any solutions related to this? Thank you.

**Comment by michaelboulton** [comment]
I'm not sure about that, you'd have to read the pytest-django documentation to see if there's a fixture that will do that kind of thing for you (or write one yourself)

**Comment by KPilnacek** [comment]
When I test a Django app I create a fixture, which fills the database with exactly the amount of data necessary for the test. I don't think there can be a solution for this, however, there are tools to help with this such as [`factory_boy`](https://factoryboy.readthedocs.io/en/latest/)

**Comment by michaelboulton** [comment]
I agree with @KPilnacek , factory boy is probably the easiest way to mock out data for tests but using it and setting up the fixtures etc. is outside the scope of Tavern. Their documentation is pretty good IIRC, it has a whole section of using it with Django.

Going to close this as the original issue should now be solved
