### ISSUE TITLE
Auto generate yaml from swagger docs? 

### ISSUE THREAD

**Issue by lingster** [taverntesting/tavern#200]
Hi, I love this project and the potential it has. Just wondering if there are plans for generating a base set of yaml test files from a swagger doc? Given that a swagger doc has all the info you need to make a request the tool could execute the api and output the response to, this would reduce the amount of time it would take to author yaml test scripts.

**Comment by michaelboulton** [comment]
We did think about this but decided against it for a few reasons:

1. Don't really have the time to try and maintain a thing to do this for swagger and inevitably openapi
2. Couldn't find a good library to abstract out swagger and openapi into a format where we could generate tests nicely

Other than that, it would be good to have a tool that took a swagger/openapi spec and generated a lot of tests from it - I thought Yelp had some tool but the only thing I found was this https://github.com/Yelp/bravado/issues/290 so maybe not...

**Comment by benhowes** [comment]
A one time import is somewhat useful, however Tavern doesn't know a great deal about how to test edge cases etc from a openapi document, so it would not let you generate very useful tests.

I suspect that the most useful aspect of this would be being able to assert the request/response schemas against the openapi spec, by referencing the openapi file. Would that be useful for you @lingster?

**Comment by lingster** [comment]
Hi @benhowes , yes I was thinking that given an openapi/swagger spec which defines all the possible REST api endpoints, then it might save the tester sometime if there was a simple tool that could read the swagger/openapi.json file and output a tavern yaml file. If the swagger docs define json inputs or outputs then that could already be included as part of the tavern yaml output.

**Comment by lingster** [comment]
Hi, I've just created a simple script/PR which showcases how to potentially generate tavern yaml file from openapi.json: 
[https://github.com/taverntesting/tavern/pull/232](url)

would be great to get some feedback.

**Comment by michaelboulton** [comment]
Closed by https://github.com/taverntesting/tavern/pull/232

Thanks for the contribution, it turned out to be easier than I expected!
