### ISSUE TITLE
Possibility of submitting json field of a POST request as a loaded object?

### ISSUE THREAD

**Issue by RobertWWong** [taverntesting/tavern#202]
I currently love simple it is to use tavern for endpoint testing.

This probably might not be the right place to ask it, but is there a way for me to make a POST request where the json: fields are not manually typed? I am using a json_schema to validate the post body, of which a lot of fields are required to be on there.

i.e.
```
include: 
  -  !include var_file.yaml
  request:
    url: "{BASE_URL:s}encounters/my_stuff"
    method: POST
    json:
        a_json_variable
___
* var_file.yaml
variables:
  a_json_variable:
    field1: etc
    ....
    fieldN: etc
```

Is there any support for this feature? I know pyresttest some what support this with a 
- body : {'file' : 'your_post_data.json'}, but that library has long since dropped support for its users.

**Comment by michaelboulton** [comment]
You can do this by using `!include` directly (it's not really documented because it was never really expected to be used that way), something like this IIRC:

```json
# json_body.yaml
{
  "a": 1,
  "b": 2,
}
```
```yaml
  request:
    url: "{BASE_URL:s}encounters/my_stuff"
    method: POST
    json: !include json_body.yaml
```

`!include` will just directly read the contents of that file into the test.

At some point in the future there might be a better way of doing this #191

**Comment by RobertWWong** [comment]
@michaelboulton Thanks for giving me more reasons to use Tavern! Definitely would love to transition over from pyresttest given the chance.  Next is to figure out how to do other equality operation for the checks.

**Comment by RobertWWong** [comment]
Hmm, I wonder if Tavern also support templating inside json objects like pyresttest? Probably need to read up on the docs more.
