### ISSUE TITLE
How can I implement retry mechanism using tavern? I have an api that returns 400 intermittently and I want to retry till I have a legit 200 response. How do I implement thus via tavern YAML implementation?

### ISSUE THREAD

**Issue by gbhangale416** [taverntesting/tavern#203]

**Comment by michaelboulton** [comment]
You can do this using `max_retries` in the request body - there's some examples in the documentation here https://taverntesting.github.io/documentation#retrying-tests

**Comment by michaelboulton** [comment]
Closing this as it appears to be solved.

**Comment by rohan-kalia** [comment]
@michaelboulton This is not working. Please work. Getting this error when trying to use max_retries:
"core.py                    164 ERROR    [u"Key 'max_retries' was not defined. Path: '/stages/2'"]
files.py                    45 ERROR    Error validating /tmp/tmpdYzzJN.yaml"

My post call with max_retries looks like:
- name: Post e number call
    max_retries: 4
    request:
      url: https://domain/request
      json:
        ewbn: "randomnumber"
