### ISSUE TITLE
Logger format issue in python 2.7

### ISSUE THREAD

**Issue by virusbogdan** [taverntesting/tavern#21]
In the **entry.py** file, **line 63**, the logger format is as follows: 
`{asctime:s} [{levelname:s}]: ({name:s}:{lineno:d}) {message:s}`

Any logging output will just print the line above and not the actual variables.

A quick fix is by replacing it with the following:
`%(asctime)s [%(levelname)s]: (%(name)s:%(lineno)d) %(message)s`

I have only tested this on python 2.7.

**Comment by michaelboulton** [comment]
Forgot that python2 only had `%` style log interpolation - now fixed in 0.2.4
