### ISSUE TITLE
Locust.io integration

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#210]
Running with locust makes it print out the first test run from pytest and no more information, but other tests do run in the background (slowly)

Quick thoughts:

- Wrap pytest_cmdline_main to cache session (see wrap_session in main.py), collection, etc. for a specific config object (or config options) to stop it having to redo it for every task
- Stop pytest overriding the logging/printing out it's own stuff somehow
- Simplify return stuff so it doesn't do as much teardown...?
- Make a custom Locust subclass to just run tavern tests, combining all of the above

**Comment by michaelboulton** [comment]
It seems like the only bit which is a bit slow is argument parsing, which can be cached. evn then, it's a very small amount of runtime. will do a bit more investigation.

**Comment by benhowes** [comment]
This doesn't appear feasible due to the slow loading time of pytest (which would be a limitation in this setting).
