### ISSUE TITLE
[Feature Request] Detailed Reporting for Tavern Testing with the format of HTML,others etc

### ISSUE THREAD

**Issue by kvenkat88** [taverntesting/tavern#217]
Hi All,

Is there any plan in pipeline to add the report generation(html or some other standard) in the near future.It would be good if we add the reporting part. It would be good if we add detailed reports capturing in the format like,
TestName
        Stages
               steps/name status with success/failure indicators,validation part and also request or response 
                passed

As of now we are using pytest junitxml generation and pytest-html plugin for reporting .These options are giving only high-level reports.It would be good if we provide details in granular level.
This feature would be very useful for Tavern wide usage for API testing.

**Comment by kvenkat88** [comment]
> Hi All,
> 
> Is there any plan in pipeline to add the report generation(html or some other standard) in the near future.It would be good if we add the reporting part. It would be good if we add detailed reports capturing in the format like,
> TestName
> Stages
> steps/name status with success/failure indicators,validation part and also request or response
> passed
> 
> As of now we are using pytest junitxml generation and pytest-html plugin for reporting .These options are giving only high-level reports.It would be good if we provide details in granular level.
> This feature would be very useful for Tavern wide usage for API testing.

**Comment by michaelboulton** [comment]
There is a half-finished implementation of hooks in https://github.com/taverntesting/tavern/pull/177 but one of the reasons it wasn't finished is that I couldn't think of which hooks would be useful to expose to users or what information would be most useful.

When that is finished there should be a hook at the end of each stage (for example) that exports the results for each stage as a dictionary, which could then be transformed into junit xml, forwarded to elasticsearch, etc. This would allow users to get more information out of Tavern than is currently possible via Pytest.

There should be some more work on that in the next month or so, but if you can list any more information that you would like to get about each stage (eg, time taken for request) we can take it into account.

**Comment by kvenkat88** [comment]
Thanks for your reply.
1.It would be good if we have request_vars hook to get the request details and I can used it in somewhere like in reporting etc..This would give users about the hostname,testing url and others.
2.Test Execution Summary hook ,it should give us no of tests executed,passed,failed,skipped,overall time taken for execution,..
3.It would be good if we have test report like Test Name(Overview of status,If passed then indicate in green,red for failed ,some color for skipped).It would give us nice representation.
4.Hierarchy should be like test_name followed by stages list info details like status,request_vars passed for the test,response_vars retrieved available.
5.Hook support for test execution bar charts/graph generation.
6.Test coverage hook.

The above feature would give users good representation of reports and coverage.

**Comment by pmneve** [comment]
Would also like to see some kind of pass/fail indication at stage level.
Also some visibility to use of xfail so those can be cleaned up when no longer need.

**Comment by ParthVividSeats** [comment]
Hey @michaelboulton , Do we have this rolled out yet?
In that case can you help me with the document to refer to for implementing this in my project?

**Comment by tking16** [comment]
Has there been any updates on Taverns test reporting? I tried implementing junit XML but the files aren't generating

**Comment by michaelboulton** [comment]
I put some experimental support for Allure (https://docs.qameta.io/allure/#_pytest) on the `feature-allure` branch which seems to produce quite a nice report:

![Screenshot_2020-12-19 Allure Report(1)](https://user-images.githubusercontent.com/3809868/102689705-272eb780-41f8-11eb-840a-b06b1be2f4eb.png)

**Comment by iferminm** [comment]
This is great! @michaelboulton 

I'm using Tavern at work and one of the main pains is the current report, it's useful but it takes additional steps to get the most out of it, so I was thinking of writing a plugin myself and contribute it but looks like you got ahead of me by 26 days.

How can I help you to get this merged? What's missing?

**Comment by michaelboulton** [comment]
This is now merged in 1.13 - if you don't have allure installed it won't do anything, but test reports can be generated as noted in the documentation https://tavern.readthedocs.io/en/latest/basics.html#generating-test-reports

**Comment by iferminm** [comment]
Oh, great!, thank you @michaelboulton. 

I'll have check it out. Again thanks a ton for the good/hard work!

**Comment by tking16** [comment]
Seconding thanks @michaelboulton! Will give it look.
