### ISSUE TITLE
Support for custom tags

### ISSUE THREAD

**Issue by deviumsweden** [taverntesting/tavern#218]
Is it possible to add option for custom tags.

Lets say I have support for:

`@pytest.mark.tags("tag1", "tag-something", "notice-the-dash")`

in the yaml file, I would like to be able to tag the test case in a similar way.

```
marks:
    - tags:
        - "tag1"
        - "tag-something"
        - "notice-the-dash"
```

That would enable the following: pytest --tags tag1 for instance.
Thanks in advance.

**Comment by michaelboulton** [comment]
Is the 'tags' marker a custom extension you are using with pytest? 

I think the behaviour you want can be achieved by just using normal pytest marks (https://taverntesting.github.io/documentation.html#marking-tests) like this:
```yaml
marks:
    - "tag1"
    - "tag2"
```
then running with `pytest -m tag1` (see pytest documentation https://docs.pytest.org/en/latest/example/markers.html).

Regarding the dashes - I did some local testing and it seems like Pytest has some issues with dashes in markers, but that is an issue in Pytest and not Tavern.

**Comment by michaelboulton** [comment]
Closing as the issue should be solved
