### ISSUE TITLE
Allow environment variable substitution in config yaml

### ISSUE THREAD

**Issue by eacmen** [taverntesting/tavern#22]
Allow variables such as sensitive API keys or other auth tokens to be set as environment variables and substituted in config.yaml when parsed at runtime (i.e. with a `$ENV{ENVNAME}` type syntax). This is standard practice for cloud-based CI solutions such a Travis, Circle CI, etc.

**Comment by benhowes** [comment]
In #6 we're looking at adding a means to pass in variables on the command line. I expect that will be the preferred way to pass env variables to tests in tavern.

**Comment by michaelboulton** [comment]
I realised this was only a couple of lines of code to do so I have implemented it in this branch https://github.com/taverntesting/tavern/tree/feature/env-var-formatting - not sure what the 'magic' variable name should be for environment variables though? I suppose that it just means people can't save a variable called ENV_VARS

**Comment by eacmen** [comment]
👍  we'll test it out and let you know of any issues.

**Comment by AmiSMB** [comment]
I have tested this branch out and it works very well for me as I am using tox with tox-docker which launches my docker container and leaves an environment variable in the form of <image-basename>_<exposed-port>_<proto> for any port listed with EXPOSE in the Dockerfile.

So now when tox-docker starts the container, pytest runs with the Tavern plugin I can use the ENV_VARS in the yaml file to get the correct port for the url to test my microservice. Good work 👍

**Comment by michaelboulton** [comment]
With #36 there is going to be a value called `tavern.env_vars` that you can format environment keys from
