### ISSUE TITLE
Parallel test execution

### ISSUE THREAD

**Issue by kvenkat88** [taverntesting/tavern#225]
Is there any possibility to run test tests in parallel using tavern. Consider a scenario , through pytest parser utility functions receiving the input from command line and have to use it in our tests. For example, have command line flag as --user a b (input is in list). By using this test i have to cover the test scenarios for both users in parallel. Through pytest we can use pytest-xdist and parameterize option to do it. Refer the below links ,

https://stackoverflow.com/questions/49699477/is-it-possible-to-execute-the-same-test-in-parallel-in-pytest
https://stackoverflow.com/questions/47439103/how-to-execute-tests-in-a-test-suite-in-parallel
https://github.com/pytest-dev/pytest-xdist

Requirement would be like test scripts should be reusable and based upon the user type test scenarios has to be validated and reported in parallel. Right now fixture don't have support for parameterization support to do this like in Pytest.

**Comment by kvenkat88** [comment]
Thanks for your reply great to hear from you. There is no documentation about parallel test execution through tavern. I can use all of the functionality available in pytest-xdist library .Could you please confirm.

**Comment by michaelboulton** [comment]
There isn't anything in Tavern that should break pytest-xdist, so you should be able to use it just fine. If you do run into any problems with it, feel free to make an issue about it.

**Comment by tommyjcarpenter** [comment]
@michaelboulton in `pytest-xdist` there is a marker to run certain tests in parallel, see https://github.com/pytest-dev/pytest-xdist/issues/325

if I want to run two tavern tests in parallel (gaurantee that my server gets two tests at the same time), how can I achieve this in the tavern yaml?

**Comment by tommyjcarpenter** [comment]
im gonna make my own issue
