### ISSUE TITLE
Tavern Does Not Support Retain When Publishing MQTT Messages

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#228]
As per the title.

[Paho MQTT defines 4 arguments for MQTT publish():](https://www.eclipse.org/paho/clients/python/docs/#publishing)

- topic
- payload
- qos
- retain

Tavern does not support 'retain'.

**Comment by michaelboulton** [comment]
I can't find a way to test this in Tavern because there isn't a nice way to keep a clean session between tests (and mosquitto doesn't seem to be retaining them n the way I would expect) but I have added it to the schema in #234
