### ISSUE TITLE
Getting error while running tavern command

### ISSUE THREAD

**Issue by srinivasgoud-n** [taverntesting/tavern#240]
Getting error while running tavern command

Steps to reproduce:
1) Create a new folder
2) Create new file - minimal.tavern.yaml with below content:
test_name: Get some fake data from the JSON placeholder API

stages:
  - name: Make sure we have the right ID
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET
    response:
      status_code: 200
      body:
        id: 1
3) pip install tavern
4) tavern-ci minimal.tavern.yaml

Expected Result: 
test_minimal.tavern.yaml::Get some fake data from the JSON placeholder API PASSED   [100%]

================================ 1 passed in 0.14 seconds =================================

Actual Result:
ERROR: not found: /home/snakka/Documents/tavern/minimal.tavern.yaml
(no name '/home/snakka/Documents/tavern/minimal.tavern.yaml' in any of [])

**Comment by varayal** [comment]
I'm facing the same issue 

any thoughts?

```
➜  api-testing tavern-ci minimal_test.tavern.yaml
==================================================== test session starts ====================================================
platform darwin -- Python 3.7.2, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /Users/varaya/Projects/api-testing, inifile:
plugins: tavern-0.22.1
collecting ...
=============================================== no tests ran in 0.00 seconds ================================================
ERROR: not found: /Users/varaya/Projects/api-testing/minimal_test.tavern.yaml
(no name '/Users/varaya/Projects/api-testing/minimal_test.tavern.yaml' in any of [])

```

**Comment by varayal** [comment]
I detected the issue this is about the file name

The file name should be called test_x.tavern.yaml, where x is a description of the contained tests.

**Comment by michaelboulton** [comment]
It seems like the documentation is a bit out of date - all the tests should be named `test_*.tavern.yaml` for them to be detected. We are planning to do a big pass on the docs in the next couple of days to try and sort out issues like this - sorry for the confusion!
