### ISSUE TITLE
How to upload images in my request body just like postman?

### ISSUE THREAD

**Issue by sridharaiyer** [taverntesting/tavern#25]
I want to upload images just like I do it in Postman. See the screenshot of my Postman session.
![screen shot 2018-02-06 at 4 01 39 pm](https://user-images.githubusercontent.com/5684178/35886618-4dabc7fc-0b57-11e8-9c55-992b5e45a247.png)

**Comment by michaelboulton** [comment]
This isn't currently supported at the moment because it's a bit irritating to open all the files that are specified in the input so that requests can pass them. It might be supported in a future version but I don't have any estimate on when it would be finished.

**Comment by michaelboulton** [comment]
This should be addressed in 0.9.0.
