### ISSUE TITLE
How to save some of the values to array

### ISSUE THREAD

**Issue by srinivasgoud-n** [taverntesting/tavern#256]
How to save some of the values to array.

As we are saving access token like below:

save:
        body:
          test_login_token: token

I would like to know if we can save multiple values to an array.

In my API request, one of the variable returns array. I want to save that in array format using above syntax. Is it possible ?

**Comment by benhowes** [comment]
@srinivasgoud-n Thanks for using Tavern! If you want to do more complicated things, that'll have to drop in to python. See https://tavern.readthedocs.io/en/latest/basics.html#saving-data-with-external-functions

**Comment by srinivasgoud-n** [comment]
save:
        $ext:
          function: utils:test_function

When use like above, I am getting below error:

 tavern.util.exceptions.BadSchemaError: Couldn't load utils:test_function
