### ISSUE TITLE
Select value of JSON response

### ISSUE THREAD

**Issue by francisr8** [taverntesting/tavern#267]
```json
[
     {"helper": {"uid": "helperID"},
        "helper2": {"uid": "helper2ID},
          "surveyID": "test"
        }
] 
```

I want to select surveyID but i can only select the whole list...

**Comment by michaelboulton** [comment]
Just going to close this to keep discussion in one issue https://github.com/taverntesting/tavern/issues/133#issuecomment-481774309

For the time being you can try using this branch https://github.com/taverntesting/tavern/pull/162 which I am keeping up to date with the master branch
