### ISSUE TITLE
Can't assert json response with key "data"

### ISSUE THREAD

**Issue by aldochristiaan** [taverntesting/tavern#27]
I want to validate my api response using tavern, but unfortunately I can't validate it because it throw exception ..
<img width="580" alt="screen shot 2018-02-07 at 21 03 33" src="https://user-images.githubusercontent.com/7087414/35921163-791464f8-0c4c-11e8-9be2-97f32109acb6.png">
somehow if i remove validation for key "data" it was success ..

So the response is:
```
{
"data": { "foo": "bar", "foo": "bar"},
"meta": { "foo": "bar", "foo": "bar"}
}
```
I can validate meta key, but not with data key.

So if use this in response:
![image](https://user-images.githubusercontent.com/7087414/35954657-7c4b9d6e-0cbd-11e8-8f31-8ec5eb660c64.png)
It will throw something like this:
![image](https://user-images.githubusercontent.com/7087414/35954679-92e4064c-0cbd-11e8-8e31-7090d2d8cff8.png)

I expect something like this:
![image](https://user-images.githubusercontent.com/7087414/35954695-af656f0e-0cbd-11e8-9acb-67e98e62f327.png)

**Comment by michaelboulton** [comment]
Just to be clear, you mean that the error message for this is misleading? I think this is sort of related to https://github.com/taverntesting/tavern/issues/17 and https://github.com/taverntesting/tavern/issues/20 , there needs to be a better way of comparing data and printing out the differences between expected and returned data

**Comment by benhowes** [comment]
@aldochristiaan keen to help, but need clarification from you. Feel free to re-open if you have more details for us.
