### ISSUE TITLE
[Feature Request] Configure tavern Pytest Hook to run certain files. eg: not prefixed with "test"

### ISSUE THREAD

**Issue by mccasey** [taverntesting/tavern#280]
With PyTest I can create a pytest.ini file and have PyTest look for test files that match a certain naming scheme. Example:
```python
# pytest.ini
python_files = check_*.py *_check.py
```
is there any way I can configure the naming scheme for tavern tests so that I don't have to rely on the default `test_*` naming scheme.

https://github.com/taverntesting/tavern/blob/master/tavern/testutils/pytesthook/hooks.py#L47

**Comment by michaelboulton** [comment]
This is currently hardcoded in `pytest_collect_file` in hooks.py, this could possibly be changed to have a config variable like
`tavern_files = check_*.tavern.yaml`
