### ISSUE TITLE
how to create the external functions for validating backend DB

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#282]
senario:

1. Using YAML will POST json rest  and data is stored in back end DB ( eg: Neo4j) .

Now above can be validated as below 2 ways .
a.  Checking response body in the step 1.( i.e same YAML as mentioned above)
b. But how can i verify the response by using external function where entity is really created in DATABASE. 
  i.e for example if back-end DATABASE is Neo4j Graph DB whether external function can be used to access the Neo4j and validate the same?

**Comment by michaelboulton** [comment]
How to actually do the validation you are asking about is specific to your use case, but there are examples of how to use external functions in the documentation which can hopefully help:

https://tavern.readthedocs.io/en/latest/examples.html#external-functions

https://tavern.readthedocs.io/en/latest/basics.html#saving-data-with-external-functions

**Comment by prasadkkl** [comment]
thanks...now able solve the above issue
