### ISSUE TITLE
Is it possible to use parametrize vals from common.yaml?

### ISSUE THREAD

**Issue by sriharshamadishetty** [taverntesting/tavern#284]

**Comment by sriharshamadishetty** [comment]
#test_sample.tavern.yaml
---
test_name: Test post a new fruit

marks:
  - parametrize:
      key:
        - fruit
        - edible
      vals:
        - [rotten, apple]
        - [fresh, orange]
        - [unripe, pear]
stages:
  - name: Create a new fruit entry
    request:
      url: "{host}/fruit"
      method: POST
      json:
        fruit_type: "{edible} {fruit}"
    response:
      status_code: 201

**Comment by sriharshamadishetty** [comment]
#test_sample.tavern.yaml

---
test_name: Test post a new fruit
marks:
  - parametrize:
      key:
        - fruit
        - edible
      vals:
        - ["{{abc}}", "{{xyz}}"]

stages:
  - name: Create a new fruit entry
    request:
      url: "{host}/api/users"
      method: POST
      json:
        name: "{fruit}"
        id: "{edible}"
    response:
      status_code: 201
      body:
        name: "{tavern.request_vars.json.name}"


#common.yaml

name: Common 
description: URL Specification

variables:

  host: https://reqres.in
  abc: fresh
  xyz: apple

output:

AssertionError: assert {'createdAt':...ame': '{abc}'} == {'name': 'fresh'} Differing items: {'name': '{abc}'} != {'name': 'fresh'} Left contains more items: {'createdAt': '2019-02-25T21:19:36.983Z', 'id': '{xyz}'} Full diff: - {'createdAt': '2019-02-25T21:19:36.983Z', 'id': '{xyz}', 'name': '{abc}'} + {'name': 'fresh'}

 **assert actual_val == expected_val AssertionError: assert '{abc}' == 'fresh' - {abc} + fresh**

**Comment by michaelboulton** [comment]
This is possible, you just need to remove the double brackets around the values (like `["{abc}", "{xyz}"]`. There are examples in the integration tests folder https://github.com/taverntesting/tavern/blob/54d33348942d0e6765e5b042164ca29d9fb07a83/tests/integration/test_parametrize.tavern.yaml#L410-L472

**Comment by sriharshamadishetty** [comment]
Hi,
When I am using like ["{abc}", "{xyz}"], now I am ended up with this error.

E   tavern.util.exceptions.MissingFormatError: ('abc',)

<string>:1: MissingFormatError

**Comment by sriharshamadishetty** [comment]
### **### When running the example you have provided (test_parametrize.tavern.yaml)**

============================================================================================== ERRORS ==================================================================================================
_____________________________________________________________________ ERROR collecting tests/integration/test_parametrize.tavern.yaml _____________________________________________________________________
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\util\dict_util.py:38: in format_keys
    formatted = val.format(**box_vars)
E   KeyError: 'global_test_string_1'

The above exception was the direct cause of the following exception:
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\testutils\pytesthook.py:276: in collect
    for i in self._generate_items(test_spec):
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\testutils\pytesthook.py:234: in _generate_items
    extra_arg = format_keys(extra_arg, fmt_vars)
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\util\dict_util.py:33: in format_keys
    formatted[key] = format_keys(val[key], box_vars)
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\util\dict_util.py:35: in format_keys
    formatted = [format_keys(item, box_vars) for item in val]
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\util\dict_util.py:35: in <listcomp>
    formatted = [format_keys(item, box_vars) for item in val]
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\tavern\util\dict_util.py:43: in format_keys
    raise_from(exceptions.MissingFormatError(e.args), e)
..\..\..\..\..\appdata\local\programs\python\python37-32\lib\site-packages\future\utils\__init__.py:400: in raise_from
    exec(execstr, myglobals, mylocals)
<string>:1: in <module>
    ???
E   tavern.util.exceptions.MissingFormatError: ('global_test_string_1',)
--------------------------------------------------------------------------------------------- Captured stderr ---------------------------------------------------------------------------------------------
Failed to resolve string [{global_test_string_1}] with variables [{}]
Key(s) not found in format: ('global_test_string_1',)

**Comment by michaelboulton** [comment]
Those tests (and your test) require using an external file or saving variables from previous stages:

- https://tavern.readthedocs.io/en/latest/basics.html#response
- https://tavern.readthedocs.io/en/latest/basics.html#including-external-files
