### ISSUE TITLE
using variable to check response status

### ISSUE THREAD

**Issue by LubGurevich** [taverntesting/tavern#285]
Hi,
Is there a way to use variables to verify response status_code?
ex:
response:
  status_code: {http_code.OK} 

with http_code.OK being  defined in external file

**Comment by benhowes** [comment]
You'd need to use an external function, see the docs here: https://tavern.readthedocs.io/en/latest/basics.html#saving-data-with-external-functions

Separately, if there is a really really good reason that the OK code needs to be configurable (and that editing it in the .tavern.yaml isn't sufficient), I feel bad for you son.

**Comment by benhowes** [comment]
There's a second example of external function usage here https://github.com/taverntesting/tavern/blob/master/example/advanced/test_server.tavern.yaml#L22, along with the `testutils` file alongside it
