### ISSUE TITLE
How to convert below request into tavern specific format

### ISSUE THREAD

**Issue by srinivasgoud-n** [taverntesting/tavern#291]
def add_user_data(self):
    self.data = {}
    self.data["id"] = 0
    self.data["name"] = "name”
    self.data["description"] = "desc"
    self.data["type"] = "type"
    self.data["task_id"] = "task_id"
    self.data["level"] = 1
    aws_key_data = {}
    aws_key_data["C_ID"] = "C_ID_VALUE"
    aws_key_data["C_KEY"] = "C_KEY_VALUE"
    aws_key_data["flag"] = "false"
    self.data["KV"] = {"name":"admin","role":"admin"}
    self.url = API end point here
    self.headers[
        "Authorization"] = "token"
    headers = self.headers
    if "Content-Type" in headers:
        del headers["Content-Type"]
        del headers["Accept"]
    files = {"data": (None, json.dumps(self.data), 'application/json')}
    response = self.session.post(self.url , files=files, headers=headers)
    assert (response.status_code == STATUS_OK)

**Comment by benhowes** [comment]
@srinivasgoud-n, please have a look through the docs, do your best and ask more specific questions if they come up. This is a "Can you do my homework for me?" type request at the moment.

All the best
