### ISSUE TITLE
How to use run() function for HTML Report generation

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#292]
Actually Via pytest we can easily generate html Report as below ( with pytest Html plugin installed)

]# py.test test_test.tavern.yaml -vv --html=report.html

But how to do the same using run?

==============================
from tavern.core import run

success = run("test_test.tavern.yaml",pytest_args=["-vv"])
==============================

How to pass the  third parameter "--html=report.html" in run() ?

**Comment by michaelboulton** [comment]
I can't try it at the moment, but does it work if you pass it to `pytest_args`? ie:
```python
success = run("test_test.tavern.yaml", pytest_args=["-vv", "--html=report.html"])
```

**Comment by prasadkkl** [comment]
thank you....tried above perfectly worked fine. Html Report generated successfully.

Could you confirm run() will return 0 for success scenario..?

**Comment by michaelboulton** [comment]
It just called pytest.main() so it should return 0 on success https://docs.pytest.org/en/latest/usage.html#calling-pytest-from-python-code

This does need documenting, I should be able to get round to that soon
