### ISSUE TITLE
What is the value of response

### ISSUE THREAD

**Issue by francisr8** [taverntesting/tavern#298]
I want to work with external functions. For example:

```
def test_function(response):
    json_str = json.dumps(response)
    resp = json.loads(json_str)
    appId = resp['appointmentId']
    return {"appointment": appId}
```

OR

```
def printresp(response):
    return {response.json()}
```

But they don't work because "response" is not compatible. How do you convert the response to JSON?

**Comment by jasonamclean** [comment]
I've used both of the following depending on the strucgure of my JSON response:
`json_response = json.loads(response.content)`
when my response has been nested inside an array
and
`json_response = response.json()`
when my response has been regular json objects

**Comment by francisr8** [comment]
If I try that, there raises an error:  TypeError: list indices must be integers or slices, not str

**Comment by michaelboulton** [comment]
Assuming this is related to #299 this is because your API is returning a list and not a dictionary. As this is not a problem with Tavern I'm closing this issue
