### ISSUE TITLE
How to share a test step between the different files? 

### ISSUE THREAD

**Issue by alexdashkov** [taverntesting/tavern#302]
Hello, I have a step with authentification where I save my token. I want to use this step in the different tests. I understand how to do it with anchors in one file but I can't place all the tests in one file (yaml format is pretty long). I can't find a way how to use it in the different files. I've tried to do it using `includes` but it doesn't work in my case.
```
includes:
  - !include common_steps.yaml
```

Can you help me please?

**Comment by michaelboulton** [comment]
You can do this by declaring a `stages` key in the included file with the stage you want (also remember to give it an `id`), then referring to it in your test by declaring the stage to be a reference:

```yaml
  - type: ref
    id: login_get_token
```

There is an example in the examples folder (https://github.com/taverntesting/tavern/tree/54d33348942d0e6765e5b042164ca29d9fb07a83/example/components) but this appears to not be documented, I will try to get around to that this weekend

**Comment by alexdashkov** [comment]
@michaelboulton Thank you for the quick response. Your solution works great!
