### ISSUE TITLE
Unable to use run() function for global configuration

### ISSUE THREAD

**Issue by sriharshamadishetty** [taverntesting/tavern#304]
#test.py
```python
from tavern.core import run

extra_cfg = {
    "variables": {
        "host": "host",
        "user": "user",
        "password": "password"
    }
}

run("test_login.tavern.yaml", extra_cfg)
```

I was able run this successfully using **Tavern:0.22.1** but, when using **Tavern:0.25.0** I am ending up with below error.

**programs\python\python37\Lib\argparse.py", line 2108, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
KeyError: 0**

**Comment by michaelboulton** [comment]
Sorry for not responding earlier, this seems to have been accidentally changed at some point
