### ISSUE TITLE
Session scope - argparsing a config object

### ISSUE THREAD

**Issue by Formartha** [taverntesting/tavern#305]
Hi,

I'm using a paramer for parsing args a global dictionary that hold configs.
The config is used to hold IPs of several components which acts as an endpoint for the given application.

I would like to use Tavern to request the values but I don't know how to do that.

any ideas?

the config looks like the following:
```
cfg = {
          'componenet_a': 'x.x.x.x',
           'componenet_b': 'y.y.y.y'
} 
```
--
EDIT: found a way to return the config object. I just left with how should I access nested value.

**Comment by michaelboulton** [comment]
Are you passing that config object in via the `run()` function? I'm not entirely sure what you're trying to do, if you could give more information I could give more advice

**Comment by Formartha** [comment]
I'll try to explain.
I'm using a dictionary which being parsed once per session. this dictionary is a config file for the tests to access (such as singleton).
I'd like to be able to fetch this object and pass it down to an api.

for example:
---
cfg = {
          'componenet_a': '127.0.0.1'
} 
---
test_name: Basic test

marks:
  - usefixtures:
      - cfg

stages:
  - name: Test myself
    request:
      url: "https://{cfg.componenet_a}:8443"
      method: GET

**Comment by michaelboulton** [comment]
Assuming you are returning it from a fixture, you will need to wrap it in a `Box` object from the box library like this

```python
import box

@pytest.fixture(name="cfg")
def get_cfg():
    cfg = {
        'componenet_a': '127.0.0.1'
    }
    return box.Box(cfg)
```

**Comment by Formartha** [comment]
Great idea.
Any native way to do that without 3rd party python pkg?
A built in utility in Tavern to access nested dict or duck typing?

**Comment by michaelboulton** [comment]
The box library is a requirement of tavern so it should be present in your environment already

**Comment by michaelboulton** [comment]
Going to close this as the original issue now seems to be fixed.
