### ISSUE TITLE
Variable error logging doesn't handle escaped curly bracket, !raw, and comments

### ISSUE THREAD

**Issue by MichielVanderlee** [taverntesting/tavern#308]
`tavern/testutils/pytesthook/error.py` `ReprdError.toterminal().read_relevant_lines()`
Does not ignore lines starting with `#` or containing `!raw`. This causes errors when using curly brackets in comments.

Version 0.25.0

**Comment by MichielVanderlee** [comment]
Took a while to figure out exactly what's going on here.
If a test fails, i.e.: response body doesn't match, then it reads the `yaml` file line by line to extract all variables via this regex: `r"(?P<format_var>{.*?})"`.

There are a few issues with this approach:
1. We read and parse comments i.e.: `# This will match the {regex}`
2. We read and parse `!raw` values. `raw_value: !raw "{uhoh}"`
3. We match incorrectly on escaped curly brackets, i.e.: ` escaped_value: "{{I'm not a variable}}"`

**Comment by michaelboulton** [comment]
Should be fixed by the above commit
