### ISSUE TITLE
Jinja template style filters?

### ISSUE THREAD

**Issue by WhileLoop** [taverntesting/tavern#31]
Any chance of getting Jinja template style filters?
Would be nice to be able to do something like 

```
body:
  json:
    mydata: "{saved_value | b64decode}"
```

**Comment by michaelboulton** [comment]
The suggested way of doing more complicated operations on format variables from here on out (such as decoding base64 strings) is going to be to use an [external function](https://taverntesting.github.io/documentation.html#saving-data-with-external-functions)
