### ISSUE TITLE
Integration in pytest broken

### ISSUE THREAD

**Issue by flazzarini** [taverntesting/tavern#315]
I've noticed that with the recent version `v0.26.1` the integration in pytest seems broken. The command line parameters `--tavern*` are no longer present.

When using `v0.22.0` the command line parameters in pytest are present

```
 $ ./env/bin/pytest --help | grep tavern
  --tavern-global-cfg=TAVERN_GLOBAL_CFG [TAVERN_GLOBAL_CFG ...]
  --tavern-http-backend=TAVERN_HTTP_BACKEND
  --tavern-mqtt-backend=TAVERN_MQTT_BACKEND
  --tavern-strict={body,headers,redirect_query_params} [{body,headers,redirect_query_params} ...]
  --tavern-beta-new-traceback
  tavern-global-cfg (linelist) One or more global configuration files to include
  tavern-http-backend (string) Which http backend to use
  tavern-mqtt-backend (string) Which mqtt backend to use
  tavern-strict (args)     Default response matching strictness
  tavern-beta-new-traceback (bool) Use new traceback style (beta)
```

When using `v0.26.1` the command line parameters are no longer present

```
$ ./env/bin/pytest --help | grep tavern
$
```

**Comment by michaelboulton** [comment]
The layout of the Pytest directories changed a bit in a previous version which I thought might cause some issues, can you try recreating the virtualenv and running it again? I can't recreate your behaviour with python 2 or 3

**Comment by michaelboulton** [comment]
Assuming this is fixed
