### ISSUE TITLE
Show test summary on test run finalization

### ISSUE THREAD

**Issue by lggomezml** [taverntesting/tavern#319]
I had the problem described on #186 and I find the `--tavern-beta-new-traceback` really useful, as it improves greatly the output of the test session

One way I think this can be improved further is moving the test summary to the end of the output logs, as it makes it easier to see which tests failed from the entire set. This currently shows at the start of the output, because it shows the tests as they run:

<img width="616" alt="Screen Shot 2019-03-22 at 10 15 57" src="https://user-images.githubusercontent.com/29546751/54825557-ab06e900-4c8c-11e9-9096-5766748a1ce3.png">

**Comment by lggomezml** [comment]
@michaelboulton if you are ok with this (and giving me some pointers) I can try to give this a shot

**Comment by michaelboulton** [comment]
This is a pytest plugin thing and there might be a pytest plugin that does it already. I'm not sure where to search but If you look at plugins like `pytest-sugar` or `pytest-instafail` it might be possible to configure them to do what you want?

**Comment by lggomez** [comment]
I see, `pytest-sugar` already improves a lot the output. So all of these packages plug into pytest on installation and one locally has to maintain and configure its own setup right?

Thanks for the explanation

**Comment by michaelboulton** [comment]
Yes, you just need to pick whichever plugins you want locally (or write your own).
