### ISSUE TITLE
When will be support http method PATCH?

### ISSUE THREAD

**Issue by vit-goncharov** [taverntesting/tavern#32]
What version will be support this?

**Comment by WhileLoop** [comment]
Since tavern uses requests it should already be possible. http://docs.python-requests.org/en/master/api/#requests.patch

Are you seeing an error?

**Comment by vit-goncharov** [comment]
Enum 'PATCH' does not exist. Path: '/stages/0/request/method - write in console this error

**Comment by WhileLoop** [comment]
Try adding it here https://github.com/taverntesting/tavern/blob/master/tavern/schemas/tests.schema.yaml#L77

**Comment by vit-goncharov** [comment]
Add new string - PATCH and it worked. Thank you. Please, add this in new version tavern
