### ISSUE TITLE
tavern_ci: command not found

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#321]
{venv} $ tavern_ci test_poc_err.tavern.yaml 
-bash: tavern_ci: command not found

I'm clearly missing something simple.
Installed tavern with pip in a pyenv virtualenv, on Mac OS High Sierra

**Comment by michaelboulton** [comment]
It's `tavern-ci` (with a dash, not an underscore)

**Comment by pmneve** [comment]
Oh my!  One of those easy to trip over patterns in the linoleum.  Thanks!
