### ISSUE TITLE
How can I implement some kind of time.sleep or pause in my test.tavern.yaml?

### ISSUE THREAD

**Issue by MonRes** [taverntesting/tavern#337]
Is any option to implement some kind of time.sleep / pause in test.tavern.yaml between two stages? 

I've got in one file POST method which send some measurement and next GET method which should receive this sended measurement but sometimes without time.sleep or pause it is a problem. 

Maybe implementation of pause from Ansible 2.7 could be good solution.

**Comment by michaelboulton** [comment]
You can add a delay before or after a test stage https://tavern.readthedocs.io/en/latest/basics.html?highlight=delaY#adding-a-delay-between-tests

**Comment by MonRes** [comment]
@michaelboulton oh great! sory for bothering you... I didn't notice this option... thank you very much!
