### ISSUE TITLE
Allow xfail at the stage level [enhancement request]

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#346]
Have occasion to want xfail on stages not critical to the purpose of the test that precede the last, critical, validation stage.

**Comment by michaelboulton** [comment]
Currently xfail is handled by Pytest fixtures so it can't easily be implemented in each stage. The way xfail works in Pytest is also that it will stop the whole test immediately, which doesn't seem to be what you want it for.

Just as a personal opinion, I don't think you should have things in your tests that you expect to _sometimes_ fail, if your test doesn't work 100% of the time or fail 100% of the time then you're not really testing the same thing which each subsequent run. If this is something you need to deal with, there is some advice in the Pytest documentation https://docs.pytest.org/en/latest/flaky.html

**Comment by pmneve** [comment]
I need to clean up test data created for a given test document whether the primary validation stage fails or not.  Skipping that stage negates the test, xfail for the entire document forces the test to exit immediately and skip the cleanup stage.  
Allowing the incorrect response code invalidates the test.   
Resetting the entire database to an initial state is not an option (and I believe it to be a last resort in any case).  
And pytest's flakiness document mentions tests that don't clean up after themselves but doesn't cover this use case.   It seems to be covered when using pytest outside of Tavern but Tavern has advantages for visibility to managers, product owners, and other developers that I'm loathe to lose.

Am looking for a way to force cleanup stages always to run (as using the application to clean up itself is preferable).  
A possible alternative is to somehow pass data needed for cleanup to a separate Tavern 'cleanup' document. 
Any suggestions?

**Comment by Birne94** [comment]
Maybe using [pytest fixtures](https://tavern.readthedocs.io/en/latest/basics.html#usefixtures) is an option here?

If you want to cleanup after each stage, you can use something along the lines of:

```python
@pytest.fixture
def cleanup_afterwards():
    try:
        yield
    finally:
        cleanup_my_resources()
```
or

```python
@pytest.fixture
def cleanup_afterwards():
    try:
        yield
    except:
        cleanup_my_resources()
        raise  # bubble up
```

The first version will call the `cleanup_my_resources` function (or whatever is needed) after the stage has completed or failed, the second version will only cleanup if the stage has failed.

You probably will need to add the fixture to each stage then.

**Comment by pmneve** [comment]
Thanks, @Birne94!

Unfortunately tavern doesn't support passing variables to fixtures yet and the clean up requires at least one dynamic id.

**Comment by Birne94** [comment]
Are the dynamic ids returned by the server and can be saved as variables in tavern? You can access those (quite hacky, unfortunately), through the `request` fixture parameter:

```python
@pytest.fixture
def my_fixture(request):
    try:
        yield
    finally:
        saved = request._parent_request._pyfuncitem.global_cfg.get('variables', {})
        print(saved)  # {"foo": "bar"}
```

@michaelboulton maybe introducing a tavern fixture (#147) would actually be useful, even if it just exposes the saved variables to the fixture. Unfortunately, subclassing `FixtureRequest` does not work straight forward since it appears to create a `SubRequest` instance internally which is then passed to the fixture.

**Comment by michaelboulton** [comment]
One of the problems with the 'tavern' fixture is how to actually nicely scope it to each test programatically (bearing in mind each test can be run in parallel, out of order, etc). I think there would also be some problem in that pytest would probably raise an error if 'strict' was turned on because 'tavern' is a non-standard fixture name.

I think there might be some way of just sending a value back from a 'yield' fixture like this

```python
@pytest.fixture(name="tavern_complicated_request_val")
def test_complicated_return_value():
    val = calculate_something_complicated()

    response = (yield val)

    expected = calculate_complicated_response()
    assert response.body["value"] == expected    
```

But I haven't really looked at how Pytest implements that, and there would need to be some kind of decision made on what the 'response' object would look like

**Comment by Birne94** [comment]
> One of the problems with the 'tavern' fixture is how to actually nicely scope it to each test programatically (bearing in mind each test can be run in parallel, out of order, etc).

Out of order execution of tests would not cause any issues as long as all stages from a single test are executed in order, which should be happening anyway. Parallel execution of tests could be worked around with thread-local storage, where each fixture holds the current state local to the executing test. Is there something else I am missing?

Another solution would be to just have the tavern fixture depend on the current request and expose its attributes through the protected variables:

```python
@dataclass
class TavernFixtureData(object):
    item: YamlItem

    @property
    def variables(self):
        return self.item.global_cfg.get('variables', {})


@pytest.fixture
def tavern(request):
    if isinstance(request, SubRequest):
        request = request._parent_request

    yaml_item = request._pyfuncitem
    assert isinstance(yaml_item, YamlItem)
    return TavernFixtureData(item=yaml_item)


@pytest.fixture
def my_fixture(tavern):
    try:
        yield
    finally:
        saved = tavern.variables
        print(saved)  # {"foo": "bar"}

```

> I think there might be some way of just sending a value back from a 'yield' fixture like this

From a quick glance at the pytest code (`fixtures.py:819`), it doesn't look like there is a way to pass parameters back to the generator:

```python
def call_fixture_func(fixturefunc, request, kwargs):
    yieldctx = is_generator(fixturefunc)
    if yieldctx:
        it = fixturefunc(**kwargs)
        res = next(it)   # <---- here -----
        finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, it)
        request.addfinalizer(finalizer)
    else:
        res = fixturefunc(**kwargs)
    return res

```

**Comment by michaelboulton** [comment]
I guess that first block of code would be a nice way of exposing variables (I checked and I was wrong about the name, I forgot that Pytest only complains about nonstandard _markers_).

Kind of irritating that you can't send something back from a test, It doesn't seem like a simple fix either.

**Comment by pmneve** [comment]
@Birne94 @michaelboulton  Thanks for the discussion!  Am at a point where I need to dig further into solving the issue and you've given avenues to explore.
