### ISSUE TITLE
Test gRPC APIs?

### ISSUE THREAD

**Issue by Alan-R** [taverntesting/tavern#347]
Is it possible to have Tavern test gRPC APIs?

(I'm not sure if that even makes sense, but it seems like it could be useful)

**Comment by michaelboulton** [comment]
I'm not opposed to it, but I wouldn't even know if it was possible or how to start implementing it!

**Comment by michaelboulton** [comment]
Going to close this for the reasons mentioned in https://github.com/taverntesting/tavern/issues/419 , if somebody wants to make one then I will happily promote it on the documentation/readme.

**Comment by kiril-me** [comment]
@Alan-R Can you take a look at #438 Does this looks like what you wanted?

**Comment by Alan-R** [comment]
The capability sounds great! I didn't read the code...

You guys are amazing!
