### ISSUE TITLE
Question: future support for starting the server?

### ISSUE THREAD

**Issue by tommyjcarpenter** [taverntesting/tavern#353]
Is it possible that Tavern could grow to include commands for actually starting the server? For example, taking a "run" command that will start the application's webserver (may be flask, tornado, gevent, etc). Or, docker commands that build/run a container that can be hit?

Tavern seems to provide no support for actually starting the server, and am just wondering if this is a "future TODO" or "never going to happen". 

It seems possible to hack this together using a combination of tox and tavern, by running some arbitrary commands in tox before running tavern, but I'm wondering whether that is something that can belong in the tavern.

**Comment by michaelboulton** [comment]
This is pretty far outside the scope of tavern, but you should be able to achieve what you want either by doing something in tox (like you are currently doing) or using a session scoped fixture https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session
