### ISSUE TITLE
A question: Have several headers entries that are identical for every stage

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#355]
Is there a way to pull those in from a single place?  fixture? !include file?

**Comment by michaelboulton** [comment]
The best way to do this at the moment is to just include an external yaml/json file with your headers in

**Comment by pmneve** [comment]
ok.  looked at yaml !include stuff.   Does the yaml need to be properly indented in the include file?

**Comment by michaelboulton** [comment]
It needs to be 'properly indented' in that it needs to be valid YAML, it doesn't need to be indented to the level of the place you are including it.
