### ISSUE TITLE
Force certain tests to run in parallel 

### ISSUE THREAD

**Issue by tommyjcarpenter** [taverntesting/tavern#359]
My issue is related to a closed issue: https://github.com/taverntesting/tavern/issues/225

In pytest-xdist there is a marker to run certain tests in parallel, see pytest-dev/pytest-xdist#325

But that seems down at the pytest level, and tavern abstracts that level away (there is no pytest file, just the tavern.yaml)

If I want to run two tavern tests in parallel (guarantee that my server gets two tests at the same time), how can I achieve this in the tavern yaml? I'm essentially trying to test the non-blocking nature of my server, and I'm trying to run two parallel requests, one of which I expect to take longer, and not block the other request.

**Comment by tommyjcarpenter** [comment]
This might just be a question, not a feature request, but I can't add my own label to nicely label it as a question.

**Comment by michaelboulton** [comment]
Each Tavern test is just a Pytest test, so if you use pytest-xdist then it will run the tests in parallel. There is no way to guarantee that two specific tests run in parallel though, as mentioned in that issue
