### ISSUE TITLE
"Not a directory" when installing in a virtualenv

### ISSUE THREAD

**Issue by afita** [taverntesting/tavern#365]
When I install tavern in a virtualenv, the egg installed in the venv site-packages is a file instead of directory.

Here's how I do it:

```
git clone https://github.com/taverntesting/tavern.git
virtualenv -p python3 --system-site-packages venv
source venv/bin/activate
cd tavern
python3 setup.py install
```

After this, when I look in venv/lib/python3.5/site-packages/ I see that tavern-0.26.3-py3.5.egg is a file instead of a directory, and executing tests fails as in issue #314.

When I install with pip, tavern is a directoy (note that the directory is not named tavern-0.26.3-py3.5.egg) and test execution works.

Currently, as a workaround, I manually unzip venv/lib/python3.5/site-packages/tavern-0.26.3-py3.5.egg and then test execution starts working.

I need to install the latest version from github because it has support for loading json test data files. The version installed with pip does not have this.

What is the proper way to install?

**Comment by afita** [comment]
I found my answer here: https://stackoverflow.com/questions/28986708/zip-safe-false-is-not-working-in-setup-py-file

So, instead of doing `python3 setup.py install`, I do:

```
python3 setup.py sdist
pip3 install dist/tavern-0.26.3.tar.gz
```

And now tavern is a directory in site-packages and test execution works.

**Comment by michaelboulton** [comment]
I forgot that there was a behavioural change and didn't upload a new version to pypi, the latest version there (0.26.4) should now work with including json files.
