### ISSUE TITLE
Fix for new pytest version

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#367]
Pytest changed their internal api so 4.6.0+ breaks tavern, currently I've just locked the version to one that works

**Comment by mikida12** [comment]
@michaelboulton what versions of tavern and pytest currently work together? I tried many combinations but couldn't get it to work:
`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 900, in _find_spec
AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'
... `

**Comment by tobwiens** [comment]
@mikida12 @michaelboulton 
The following configuration works fine for us: 
`platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0`
with `plugins: tavern-0.22.1`

The configuration `platform linux -- Python 3.6.8, pytest-5.0.0, py-1.8.0, pluggy-0.12.0` doesn't work for us, currently.

**Comment by okuryu** [comment]
It already fixed in the master, but it isn't published to PyPI yet.

I have the following workaround for now.
```
pip install tavern 'pytest<4.6.0'
```

**Comment by michaelboulton** [comment]
Result of #313 

0.26.5 is now pushed to pypi with hardcoding pytest <4.6.0.

Still need to actually fix the underlying issue but it's a bit annoying as mentioned in the original issue

**Comment by michaelboulton** [comment]
https://github.com/pytest-dev/pytest/issues/5519 Missed this earlier, but pytest 5 doesn't support python 2 so this will have to be a 1.0 change

**Comment by erichonkanen** [comment]
just discovered this lib but we are using latest pytest `v5.3.1`, is this not going to be supported in 1.0? how can I use this?

**Comment by michaelboulton** [comment]
Should have been closed a while ago
