### ISSUE TITLE
HTTP Plugin Not Recognized

### ISSUE THREAD

**Issue by sdetDouglass** [taverntesting/tavern#368]
Tavern is unable to recognize a custom plugin, in this implementation the folder is named 'plugin'.
Running the command 'pytest --tavern-http-backend nossl tests/test_feature_group_endpoint.tavern.yaml' should pick up the plugin but instead the error "E   stevedore.exception.NoMatches: No tavern_http extensions found" is returned.

Attached is setup.cfg below that resides in the project's root:

```ini
[options]
packages = find:
include_package_data = True

[options.entry_points]
tavern_http =
    nossl = plugin.tavernhook

[tool:pytest]
tavern-global-cfg =
    common/common.yaml
    common/fr_urls.yaml
    models/enumeration_endpoint.yaml
addopts =
    --tb=short
    -p no:logging
```

Any ideas?

**Comment by stephsamson** [comment]
I've reproduced this error using the `tavern-flask` plugin as well.

**Comment by michaelboulton** [comment]
Silly question, but have you installed the package you're using the plugin from? Plugins will only be picked up if the package has been installed.

I also can't reproduce this with the tavern-flask plugin, though that is very out of date and I get an error when it tries to make the request...

For reference, Tavern uses the plugin system to load the 'default' behaviour:
https://github.com/taverntesting/tavern/blob/776b784dca4586003a44eb40b312227a19081fbc/tavern/testutils/pytesthook/util.py#L107-L108
https://github.com/taverntesting/tavern/blob/776b784dca4586003a44eb40b312227a19081fbc/tavern/plugins.py#L104-L115

**Comment by stephsamson** [comment]
@michaelboulton yes, I have the plugin installed, installed it with `pip install -e git+https://github.com/taverntesting/tavern-flask.git#egg=tavern-flask` :)

**Comment by michaelboulton** [comment]
I'm still unable to reproduce this so I've just bumped stevedore to the latest 3.x version in the hopes that it fixes the issue.
