### ISSUE TITLE
Command to run a single test from a file

### ISSUE THREAD

**Issue by barryallen94** [taverntesting/tavern#369]
What is the command to run a single tavern test from a file comprising of several tests?

**Comment by ramennoodles20** [comment]
In linux use the -k argument an give it the name of the test or tests you want to run 
see this SO question for more info https://stackoverflow.com/questions/36456920/is-there-a-way-to-specify-which-pytest-tests-to-run-from-a-file

**Comment by markcorr9** [comment]
@barryallen94, what @ramennoodles20 said should work, but I will try to expand on it.

You could do that with the help of "marks". Just provide a name under "marks" for each of your tests. And when you want to run that particular test, mention the name of it. [The docs](https://tavern.readthedocs.io/en/latest/basics.html?highlight=marks#marking-tests) have some good examples. You could either run one test or ignore one and run the rest and so on, like:
`py.test -m "login"` or `py.test -m "not login"` (this would run all tests other than login.).

**Comment by sriharshamadishetty** [comment]
This might help you https://tavern.readthedocs.io/en/latest/basics.html#using-the-run-function

**Comment by michaelboulton** [comment]
As mentioned above, this is handled by Pytest, and the Pytest flags can be passed to the `run` function if you're using it.
