### ISSUE TITLE
Implement possibility to add a custom cookie to the request

### ISSUE THREAD

**Issue by przemek-sl** [taverntesting/tavern#374]
Tavern has now support for cookies (requested in https://github.com/taverntesting/tavern/issues/23). However, there is no way to provide a custom string in cookie.
We can only send a cookie that was returned in a previous response.

I think many people would appreciate this feature. It would be very helpful for testing endpoints that are protected and require for example a JWT in cookie.

**Comment by tcaraccia** [comment]
This would be so amazing.
Im having challenges to add a cookie on my first request.

**Comment by zeph** [comment]
please... needed

**Comment by michaelboulton** [comment]
Should be possible by adding a 'cookie' block to the request and making it take either a string (which could be a format variable) or a $ext function which dynamically calculates it
