### ISSUE TITLE
Parse lists returned by API

### ISSUE THREAD

**Issue by ramennoodles20** [taverntesting/tavern#375]
Is it currently possible to save an element from a list returned from an API for use in another stage? 

So far I have tried 

```
save: 
      body:
         0: savedElement
```
though this gives me a 

`AttributeError: 'dict' object has no attribute 'split'`

I suspect this has something to do with the way response.py treats the received object but wouldn't it be possible to treat it as a list if the key received is an index?

**Comment by michaelboulton** [comment]
The key used in a 'save' block is the name of the variable to save it to, and the value is the JMES path to it in the response. It should be like this:

```yaml
      save:
        body:
          savedElement: "[0]"
```

Note the quotes around the zero like `"[0]"` - without them it will raise an error because the YAM l loader will interpret it as a list
