### ISSUE TITLE
cannot apply filterwarnings mark in any expected way

### ISSUE THREAD

**Issue by graingert** [taverntesting/tavern#376]
I've create a repo showing my different attempts:

https://github.com/graingert/tavern-filterwarnings/commits/master

First I try to simply add a mark with the `- marks: ` option

https://github.com/graingert/tavern-filterwarnings/blob/4c828adc16b6fc2acb8ab0e679fa68ec7e6daa9a/test_minimal.tavern.yaml#L2-L3

I get an invalid schema

then I try to add it as a list item:

I get an internal error from pytest

https://github.com/graingert/tavern-filterwarnings/blob/63eb8c756a3ed047b56c22dc15a02439a32e73e6/test_minimal.tavern.yaml#L2-L4

then I try to mark the request in a fixture

https://github.com/graingert/tavern-filterwarnings/blob/53abce69b0b4990fed36adf3298eefa63c68f7ee/conftest.py#L8-L12
This has no effect, which is very strange and might be a pytest bug

the only successful way was to use a yield fixture with catchwarnings:
https://github.com/graingert/tavern-filterwarnings/blob/d34689348a27a99b3ac23cb7e402bf7246c66d73/conftest.py#L8-L14

**Comment by michaelboulton** [comment]
Unfortunately the 'special' pytest fixtures (like parametrize and skipif) require a bit of special handling inside tavern to work properly so filterwarnings might need some looking at as well
