### ISSUE TITLE
Printing the variables passed in yaml

### ISSUE THREAD

**Issue by devang-s** [taverntesting/tavern#378]
Suppose I am passing trace-id using the !uuid or using referring fixtures to pass values into the request(passing with {fixture-name})and I want to see the values passed.

Is it possible to do so?

**Comment by michaelboulton** [comment]
This isn't possible easily, but you can add a hook that will run before each stage which will give you the test dictionary and the variables (see here: https://tavern.readthedocs.io/en/latest/basics.html#before-every-test-run)
