### ISSUE TITLE
Unordered lists validation

### ISSUE THREAD

**Issue by dtitov** [taverntesting/tavern#380]
Hi,

I have an API returning a sublist in JSON, but this list does not have a fixed order, so sometimes entries are rearranged. 

It seems that Tavern is not capable of handling such case, because when I define a list with YAML markup, Tavern tries to validate it with respect to the order of the entries.

Is it possible to implement it or work it around somehow?

**Comment by michaelboulton** [comment]
This isn't possible as the order of the items in a list in JSON have meaning, if you want to check you'll need to write an external function to do it https://tavern.readthedocs.io/en/latest/basics.html#calling-external-functions

**Comment by dtitov** [comment]
I know that the order matters, but there are other libraries in a variety of languages for creating JSON-based tests, which allow one to ignore the order. 

Take a look at the example: https://www.baeldung.com/jsonassert 

There's `JSONCompareMode.LENIENT` option introduced, which allows ignoring the order in JSON arrays:
```java
String result = "[Alex, Barbera, Charlie, Xavier]";
JSONAssert.assertEquals(
  "[Charlie, Alex, Xavier, Barbera]", result, JSONCompareMode.LENIENT);
```

I believe that such functionality should be extremely simple to implement, so I don't really see a reason to ignore such a useful feature. Because in my cases, from my experience, the order is not important for the receiving side, thus endpoint does not guarantee this order.

**Comment by pythrick** [comment]
I just found out this was actually implemented and works: 

> To match the last case you can use the special setting list_any_order. This setting can only be used in the ‘json’ key of a request, but will match list items in any order as long as they are present in the response.

https://tavern.readthedocs.io/en/latest/basics.html?highlight=strict#effect-of-different-settings
