### ISSUE TITLE
Marks for pytest

### ISSUE THREAD

**Issue by rebecca-makar** [taverntesting/tavern#383]
Are all pytest marks supported if extensions are added?
Trying to use pytest dependency: https://pytest-dependency.readthedocs.io/en/latest/usage.html#marking-dependencies-at-runtime

I keep getting formatting errors and I am unsure if it is me or if only certain marks are supported.

Thanks!

**Comment by michaelboulton** [comment]
It depends on how that extension works really, can you post an example of something you're trying to do that isn't working?
