### ISSUE TITLE
Multiple MQTT Responses to a Single Request 

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#385]
For HTTP the single request/single response model seems to be the norm (in my limited experience) however a single MQTT message might elicit more than one response. For example,

App A
  - sends a request to display some text on a screen

App B
  - receives the request
  - determines that the request is valid
  - writes the text to the screen hardware
  - receives the hardware acknowledgement
  - publishes a response to App A
  - publishes the screen update to the rest of the world

Ideally, the Tavern Test for this would look something like:

    test_name: display

    paho-mqtt: *mqtt_spec

    stages:
      - name: Send text request
        mqtt_publish:
          topic: screen/request
          json:
            line_no: 1
            text: "Happy Christmas"
        mqtt_response:
          topic: screen/data
          json:
            line_no: 1
            text: "Happy Christmas"
          timeout: 5
        mqtt_response:
          topic: screen/response
          json:
            status: "OK"
          timeout: 5

(similar to the 'MQTT message in the same stage' example in the documentation, but with 2 mqtt_responses.

This validates OK, but does not work.

I set up my test harness to respond as follows:

    ('Received:', u'screen/request', '{"line_no": 1,"text": "Happy Christmas"}')

    ('Received:', u'screen/data', '{"line_no": 1,"text": "Happy Birthday"}')
    ('Received:', u'screen/response', '{"status": "OK"}')

Obviously the first response is incorrect, yet Tavern happily passes the test.

    (python3_5) vagrant@ubuntu-xenial:/git/Temp$ py.test -v --tavern-beta-new-traceback --html=test_report.html
    ============================= test session starts ==============================
    platform linux -- Python 3.5.2, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- /home/vagrant/VirtualEnvironments/python3_5/bin/python3.5
    cachedir: .pytest_cache
    metadata: {'Python': '3.5.2', 'Platform': 'Linux-4.4.0-146-generic-x86_64-with-Ubuntu-16.04-xenial', 'Plugins': {'html': '1.20.0', 'metadata': '1.8.0', 'tavern': '0.26.3'}, 'Packages': {'pytest': '4.4.1', 'pluggy': '0.9.0', 'py': '1.8.0'}}
    rootdir: /git/TavernTests/Temp
    plugins: tavern-0.26.3, metadata-1.8.0, html-1.20.0
    collected 1 item                                                               

    test_display.tavern.yaml::display PASSED                             [100%]

    - generated html file: /git/TavernTests/Temp/test_report.html -
    =========================== 1 passed in 0.79 seconds ===========================

Reversing the order in which the responses are published makes no difference but reversing the order in which they are tested does correctly fail the test. Of course, in that case, if the text was correct but the status was incorrect then we're back to square one.

So it appears that Tavern only considers the last mqtt_response when evaluating the result.

I tried doing it as 2 stages:

    stages:
      - name: Stage 1 - Send text request
        mqtt_publish:
          topic: screen/request
          json:
            line_no: 1
            text: "Happy Christmas"
        mqtt_response:
          topic: screen/data
          json:
            line_no: 1
            text: "Happy Christmas"
          timeout: 5

      - name: Stage 2 - Verify status
        mqtt_response:
          topic: screen/response
          json:
            status: "OK"
          timeout: 5

but this fails validation, as it seems you can't have a response without an associated request, so I have applied the following work around:

      - name: Stage 2 -Verify status
        mqtt_publish:
          topic: dummy
        mqtt_response:
          topic: screen/response
          json:
            status: "OK"
          timeout: 5

This enables the tests to run correctly but looks incredibly naff and, even though commented in the scripts, causes questions to be asked during review.

So my question is twofold:

1. Is it a bug and, if so, can it be fixed?
2. If not then is there a better way of addressing the issue?

**Comment by michaelboulton** [comment]
In your first attempt, the second mqtt_response block will just override the first one because of how YAML works (subsequent keys override previous ones).

This isn't really a 'bug' but it is a missing feature, `tavern.plugins.get_verifiers` is currently hardcoded to only get one response per session but I think that is the only place where that assumption is made so it _might_ not be too difficult

**Comment by dt4k** [comment]
We're hitting the same issue in our usecase. Can I expect any update here?

**Comment by michaelboulton** [comment]
I forgot to reply to this one easrlier, but - I looked at it and it's mainly pwkalify not being able to do complicated enough validation which makes this one annoying to do, it would require switching to another library to do the validation

**Comment by burritoIand** [comment]
this would be a great feature, just ran into it when testing a response that receives two separate mqtt responses

**Comment by michaelboulton** [comment]
I forgot to mention this earlier but this should now be possible in the 2.0 release (in alpha release on pypi), for example https://github.com/taverntesting/tavern/blob/011633eb684ebf467ef177fafbbf2085f70a90c4/example/mqtt/test_mqtt.tavern.yaml#L445-L457

**Comment by RFRIEDM-Trimble** [comment]
After testing this out, it appears that it works great, until the mqtt messages arrive out of order.

In my use case, I publish one message, and expect four messages back, on the same topic, all providing state updates. 

As a workaround, I tried increasing the retries. 

For this to work with all QOS, ideally there is a way to set the `mqtt_response`  object such that order of responses does not matter.

**Comment by michaelboulton** [comment]
I neglected to realise that could be the case with MQTT, it probably just needs to start a separated thread for each response and collect it at the end.

**Comment by michaelboulton** [comment]
I'm going to close this in favour of https://github.com/taverntesting/tavern/issues/786 , now this original issue has been solved (but doesn't necessarily work properly, as tracked in that issue )
