### ISSUE TITLE
Would it be possible to set colors in console output? Let's say red for ERROR, blue for PASS

### ISSUE THREAD

**Issue by ankanch** [taverntesting/tavern#387]
When I got a lot of test case, it just become difficult to search for which test case failed.

Would it be better with colored output text?

In current version of tavern , can we achieve this ?

**Comment by ankanch** [comment]
I'm currently achieve this by this command:
`./test.sh | grep --color=always ' FAILED \|ERROR\|WARNING'`
simple and easy.

**Comment by michaelboulton** [comment]
Test output is handled by Pytest itself, there are a few plugins like https://github.com/Frozenball/pytest-sugar or https://github.com/gowtham-sai/pytest-pspec which make the output a bit fancier but this isn't something managed by Tavern.
