### ISSUE TITLE
[question] there is a way to use Tavern validating response in a JSON Schema?

### ISSUE THREAD

**Issue by dbarenas** [taverntesting/tavern#388]
Im looking for a feature option like this one https://gist.github.com/nmarley/afe61a36f71ed1e4a9728c0f5f6f7f6f

the idea is call in the response the schema with the format json schema.

**Comment by michaelboulton** [comment]
https://tavern.readthedocs.io/en/latest/basics.html#built-in-validators You can use pykwalify to validate JSON schemas, but if you need to validate using jsonschema you'll need to write an external function to do it.
