### ISSUE TITLE
Is there any way in Tavern to handle GET that returns only part of data (i.e. paginated)?

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#389]
Need to check for specific expected values in a response that only returns 20 rows at a time and the target values are not guaranteed to be in the first page.   Can this be done in a single stage? Or do I need to do this in an $ext function?  Can't know the number of pages until the first response ('hasMore', 'lastPage'

**Comment by michaelboulton** [comment]
This is a pretty specific use case, I think this would have to be done in an external function

**Comment by michaelboulton** [comment]
Closing as this is too specific to really do internally, a lot of systems do pagination very differently
