### ISSUE TITLE
saved variable in multi-stage test not working 

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#391]
senario:
1) saved ETAG value in first stage using varibale.
2) when using this variable second stage i.e assigned above variable to headers in 2nd stage,but fuound etage value as 'ETag': '"0"'.

Expected behaviour:
    How to strip "" from the variable in TAVREN YAML?

Log:
sessions = {'requests': <requests.sessions.Session object at 0x7f329a28d710>}
stage = {'name': 'Editing subtype of Equipment', 'request': {'headers': {'content-type': 'application/json', 'ETag': '{etagVal...l': '{protocol:s}://{host}:{port}/api/equipment/{uuid_generator}'}, 'response': {'status_code': 200}, 'delay_after': 5}
tavern_box = <Box: {'env_vars': {'XDG_SESSION_ID': '4288', 'HOSTNAME': 'mdffun09', 'M2': '/jmeter/tools/apache-maven-3.3.9/bin', 'T...ers': {'content-type': 'application/json', 'ETag': '"0"'}, 'verify': True, 'stream': False, 'allow_redirects': False}}>
test_block_config = {'backends': {'http': 'requests', 'mqtt': 'paho-mqtt'}, 'description': 'Login information for test server', 'name': 'Common test information', 'strict': [], ...}

**Comment by markcorr9** [comment]
Can you post your code here? It's easier and quicker that way.

**Comment by prasadkkl** [comment]
Below is the Tavern YAML:

---
test_name: "PATCH  RICH ASSOCIATION BTW EQUIPMENT AND PATH"

marks:
  - usefixtures:
    - uuid_eq
    - rid_ass_term

stages:
  - name: "GET The ETAG Value of the node"
    request:
      headers:
        content-type: application/json
        If-None-Match: "9999"
      method: GET
      url: "{protocol:s}://{host}:{port}/api/equipment/{uuid_eq}/path/{rid_ass_term}"
    response:
      save:
        headers:
          etag_val : ETag
      status_code: 200
    delay_after: 5
	
  - name: "PATCH for Rich Association"
    request:
      headers:
        content-type: application/json
        ETag: "{etag_val}"
      json:
        ldn: PathTerminatesOn_1
        assocname: telecom
      method: PATCH
      url: "{protocol:s}://{host}:{port}/api/equipment/{uuid_eq}/path/{rid_ass_term}"
    response:
      status_code: 200
    delay_after: 5

**Comment by prasadkkl** [comment]
In Above yaml  1st stage will read/store the Etag value i.e as etag_val. And in Second Stage ETag value is assigned value from 1st Stage .ie "{etag_val}".

Then from log i.e found as ETag': '"0"' i.e extra "" is padded.  Actually Expected value should be i.e ETag': '0'

**Comment by michaelboulton** [comment]
If you are returning the etag value as an integer, you need to use a type token tag https://tavern.readthedocs.io/en/latest/basics.html#type-conversions to convert it to an int like this in the second stage:
```yaml
        ETag: !int "{etag_val}"
```

If you are actually returning it in the header as (literally) `'0'`, ie `Etag: '0'` then that is how it will be returned by Tavern, with the single quotes intact. If you need to remove them, you'll need to to it yourself by calling an external function https://tavern.readthedocs.io/en/latest/basics.html#saving-data-from-a-response . Something like this (just some pseudocode):

```python
def remove_etag_quotes(response):
  return response.headers.get("Etag").replace("'", "")
```

**Comment by michaelboulton** [comment]
Closing as I assume it's fixed
