### ISSUE TITLE
'cannot define an empty value in test'

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#407]
Getting 'BadSchemaError cannot define an empty value in test - either give it a value or explicitly set it to None' at the indicated line in the snippet below.
Am using Tavern 0.27.0.
I'm not clear about what is amiss and how it would look fixed.

```    request:
      url: "{host}/{api_ver}/profiles/"
      method: GET
      headers:
        Accept: 'application/json, text/plain, text/html, */*'
        Accept-Encoding: 'gzip, deflate, br'
        Accept-Language: 'en-US,en;q=0.9'
        Authorization: "JWT {encode_web_token}"
        case_name: "BP-5847-001B {api_ver}"
    response:
      status_code: 200
      headers:
        content-type: "application/json"
      body:
        data:
        $ext:
          function: api_helpers:check_enum_length
          extra_kwargs:
            jmes_path: data
            operator: gt
            expected: 0
            stage: "BP-5847-001B"
            api: "{api_ver}"
```
Thanks!

**Comment by michaelboulton** [comment]
It is giving an error because the 'body' key is empty , are you trying to verify that it returns an empty response body?

**Comment by pmneve** [comment]
script worked ok until I updated to 0.27.0.
just trying to run the $ext method.

**Comment by pmneve** [comment]
The line 'data:' appears to be the culprit.  will try removing it.

**Comment by pmneve** [comment]
That was indeed the culprit.

**Comment by iamramizansari** [comment]
In my case i was using variable without quotes
`variable: {tavern.env_vars.variable}`
using it with quotes solved the problem
`variable: "{tavern.env_vars.variable}"`
