### ISSUE TITLE
Change to save in 0.27.0 is painful

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#414]
All of my scripts save dict objects.
Building and testing external scripts to replace them is prohibitive at the moment. (am converting to python 3 . . .)
Will stay with 0.26.4 for now.

Any plans to again support dict, list objects in save?

**Comment by michaelboulton** [comment]
Can you give an example of what you mean? I didn't think it was possible to 'save' a non-string/int/float value before , or what you would do with it after you saved it

**Comment by pmneve** [comment]
```---
test_name: Institution allowed updates (BP-5845-009)

strict: false

includes:
  - !include ../../common.yaml

marks:
  - parametrize:
      key: api_ver
      vals:
        - v2
        - v3
  
  - usefixtures:
      - encode_web_token
      - institution_allowed_updates
      - institution_allowed_updates_expected
      - institution_db_column_order

stages:
  - name: 5845-009A POST instantiate institution name only
    request:
      url: "{host}/{api_ver}/institutions/"
      method: POST
      json:
        name: "Felinuis Nice BP-5845-009"
      headers:
        Accept: 'application/json, text/plain, */*'
        Accept-Encoding: 'gzip, deflate, br'
        Accept-Language: 'en-US,en;q=0.9'
        Authorization: "JWT {encode_web_token}"
        case_name: "BP-5845-009A {api_ver}"
    response:
      status_code: 200
      headers:
        content-type: "application/json"
      save:
        body:
          institution: data  ####data is dict
  
  - name: 5845-009B PUT set allowed fields
    request:
      url: "{host}/{api_ver}/institutions/{institution.id}/"    ### using here
      method: PUT
      json: !include ../../data/institutions/institution_allowed_updates.yaml```

**Comment by michaelboulton** [comment]
Ok, I guess https://github.com/taverntesting/tavern/issues/191 was already done and I didn't realise it, I'll revert that change seeing as nobody else ever raised an issue about unexpected behaviour

**Comment by pmneve** [comment]
Michael, 0.28.0 still doesn't allow dict or list objects in save.   I see that 0.29.0 has the change but it's not on pypi yet.
Will try again when it's there.

**Comment by pmneve** [comment]
0.30.0 works! And thanks for the 'verify_response_with' function that makes multiple validation functions visible directly in the script!
