### ISSUE TITLE
[Question] Tavern tests used in performance testing

### ISSUE THREAD

**Issue by mrychlicka** [taverntesting/tavern#425]
Is there any possibility to use tests created with tavern in any well known performance test tool like JMeter of Locust?

**Comment by michaelboulton** [comment]
There currently isn't a way to do it - it is technically possible to write a custom locust wrapper that calls pytest which then calls tavern, but it is slow and flaky. Taurus http://gettaurus.org/docs/ExecutionSettings/ will let you write tests that are similar to Tavern for things like Gatling but there isn't a way to convert between the two.

**Comment by mrychlicka** [comment]
Thank You for your answer :)
