### ISSUE TITLE
Value mismatch in body: Type of returned data was different than expected

### ISSUE THREAD

**Issue by harshabugg** [taverntesting/tavern#426]
Hi,
I am getting the following error when running test 

ERROR    tavern.response.base:base.py:47 Value mismatch in body: Type of returned data was different than expected (expected = .........some data here......(type = <class 'tavern.util.dict_util.format_keys.<locals>.InnerFormattedString'>), actual = ......some data here.....(type = <class 'dict'>))

I am storing the response of  a request in a json file. If I use the the directive "!include <filename.json>" to compare the response of another request the test passes. But if I define a function under fixture which reads the same file and returns data using json.load() the test fails with the error i have described above. 

The reason I am using fixtures is !include directive does not work at run time. If I have a response being logged to json file and if i want to "include" the file after the latest data has been logged, there is no way to achieve this. 

Please help.

Regards,
Harsha

**Comment by michaelboulton** [comment]
If you use a fixture then the return value will be converted to a string, you can't return a 'complex' json value from a fixture. There currently isn't a way to save an entire response and use it in the next response

**Comment by harshabugg** [comment]
Thank you. Could you please recommend a solution.

**Comment by harshabugg** [comment]
Hi, 
Is this possible to get a solution for this issue using rest plugin's?
Regards,
Harsha

**Comment by michaelboulton** [comment]
There currently isn't a way to reuse a whole block from a previous request, only single values or _part_ of a request

**Comment by michaelboulton** [comment]
Done in 0.34.0 https://tavern.readthedocs.io/en/latest/basics.html#including-raw-json-data
