### ISSUE TITLE
Race Condition When Publishing to an MQTT Topic

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#427]
When Tavern processes a stage it appears to
1. subscribe to the mqtt_response topic
2. publish to the mqtt_publish topic

In this way it ensures that the test is ready to receive the response before it publishes.

However, there is a race condition in **tavern._plugins.mqtt.client:client.py** when subscribing to a topic which impacts this method and, in some cases, can cause a fail.

Procedure "subscribe" calls the paho function "subscribe" and creates a list item, '_subscribed[x]', based on the returned 'mid' value, containing a tuple  ('topic', False) [_Lines 298-301_].

The callback procedure "_on_subscribe" is called on receipt of a SUBACK from the broker. Here it looks in the '_subscribed' list to match the SUBACK's 'mid'. If successful the list item is updated to ('topic', True) and 'topic' is considered subscribed [_Lines 312-315_].

Subsequently, when the "publish" procedure is invoked the '_subscribed' list is iterated and a second list 'to_wait_for' is made of any entries not marked as True [_Line 243_]. If this list is empty the publish is made otherwise the procedure sleeps for a short while before checking again. This is repeated until a timeout ('_connect_timeout') is reached. The publish is then made regardless, with a warning message [_Lines 249-265_].

Consider the following test case

>paho-mqtt: *mqtt_spec
>
>stages:
>
>\- name: Configure Simulator RAM Test to report Fail
&nbsp;&nbsp;mqtt_publish:
&nbsp;&nbsp;&nbsp;&nbsp;topic: dcpsim/test/config
&nbsp;&nbsp;&nbsp;&nbsp;json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ram_test: !bool false
&nbsp;&nbsp;mqtt_response:
&nbsp;&nbsp;&nbsp;&nbsp;topic: dcpsim/dcpsim_response
 &nbsp;&nbsp;&nbsp;&nbsp;json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result_code: 0
&nbsp;&nbsp;&nbsp;&nbsp;timeout: 1
>
>\- name: Request RAM Test - expecting Fail
&nbsp;&nbsp;mqtt_publish:
&nbsp;&nbsp;&nbsp;&nbsp;topic: dcp/run_test
&nbsp;&nbsp;&nbsp;&nbsp;json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;test_type: 1
&nbsp;&nbsp;mqtt_response:
&nbsp;&nbsp;&nbsp;&nbsp;topic: dcp/test_results
&nbsp;&nbsp;&nbsp;&nbsp;json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ram_test: !bool false
&nbsp;&nbsp;timeout: 1
>
> \- name: Configure Simulator RAM Test to report OK
&nbsp;&nbsp;mqtt_publish:
&nbsp;&nbsp;&nbsp;&nbsp;topic: dcpsim/test/config
&nbsp;&nbsp;&nbsp;&nbsp;json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ram_test: !bool true
&nbsp;&nbsp;mqtt_response:
&nbsp;&nbsp;&nbsp;&nbsp;topic: dcpsim/dcpsim_response
&nbsp;&nbsp;&nbsp;&nbsp;json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result_code: 0
&nbsp;&nbsp;timeout: 1

On a good day this is what happens (_I changed all occurrences of logger.debug in client.py to logger.warning_)

>------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.mqtt.client:client.py:297 SUBSCRIBING to topic 'dcpsim/dcpsim_response'
WARNING  tavern._plugins.mqtt.client:client.py:302 Subscribed to topic 'dcpsim/dcpsim_response' with mid '1'
WARNING  tavern._plugins.mqtt.client:client.py:315 Successfully subscribed to 'dcpsim/dcpsim_response' with mid '1'
WARNING  tavern._plugins.mqtt.client:client.py:258 Finished subcribing to all topics
WARNING  tavern._plugins.mqtt.client:client.py:297 SUBSCRIBING to topic 'dcp/test_results'
WARNING  tavern._plugins.mqtt.client:client.py:302 Subscribed to topic 'dcp/test_results' with mid '4'
WARNING  tavern._plugins.mqtt.client:client.py:315 Successfully subscribed to 'dcp/test_results' with mid '4'
WARNING  tavern._plugins.mqtt.client:client.py:258 Finished subcribing to all topics
WARNING  tavern._plugins.mqtt.client:client.py:297 SUBSCRIBING to topic 'dcpsim/dcpsim_response'
WARNING  tavern._plugins.mqtt.client:client.py:302 Subscribed to topic 'dcpsim/dcpsim_response' with mid '8'
WARNING  tavern._plugins.mqtt.client:client.py:315 Successfully subscribed to 'dcpsim/dcpsim_response' with mid '8'
WARNING  tavern._plugins.mqtt.client:client.py:258 Finished subcribing to all topics

However, on a bad day (most days) this is what happens

>------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.mqtt.client:client.py:297 SUBSCRIBING to topic 'dcpsim/dcpsim_response'
WARNING  tavern._plugins.mqtt.client:client.py:302 Subscribed to topic 'dcpsim/dcpsim_response' with mid '1'
WARNING  tavern._plugins.mqtt.client:client.py:315 Successfully subscribed to 'dcpsim/dcpsim_response' with mid '1'
WARNING  tavern._plugins.mqtt.client:client.py:258 Finished subcribing to all topics
WARNING  tavern._plugins.mqtt.client:client.py:297 SUBSCRIBING to topic 'dcp/test_results'
WARNING  tavern._plugins.mqtt.client:client.py:319 Got SUBACK message with mid '4', but did not recognise that mid
WARNING  tavern._plugins.mqtt.client:client.py:302 Subscribed to topic 'dcp/test_results' with mid '4'
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 0.25 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 0.50 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 0.75 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 1.00 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 1.25 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 1.50 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 1.75 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 2.00 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 2.25 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 2.50 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 2.75 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results']' after 3.00 seconds
WARNING  tavern._plugins.mqtt.client:client.py:269 Did not finish subscribing to '%s' before publishing - going ahead anyway
WARNING  tavern._plugins.mqtt.client:client.py:297 SUBSCRIBING to topic 'dcpsim/dcpsim_response'
WARNING  tavern._plugins.mqtt.client:client.py:319 Got SUBACK message with mid '8', but did not recognise that mid
WARNING  tavern._plugins.mqtt.client:client.py:302 Subscribed to topic 'dcpsim/dcpsim_response' with mid '8'
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 0.25 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 0.50 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 0.75 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 1.00 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 1.25 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 1.50 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 1.75 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 2.00 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 2.25 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 2.50 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 2.75 seconds
WARNING  tavern._plugins.mqtt.client:client.py:264 Not finished subcribing to '['dcp/test_results', 'dcpsim/dcpsim_response']' after 3.00 seconds
WARNING  tavern._plugins.mqtt.client:client.py:269 Did not finish subscribing to '%s' before publishing - going ahead anyway

What is happening here is that the SUBACK arrives following the call to paho "subscribe" but before the "_subscribed[x]" entry is created. The callback "_on_subscribe" then checks for the non-existent "_subscribed[x]" entry and logs a warning.

Control then passes back to the main "subscribe" procedure where the "_subscribed[x]" entry is belatedly created with a value of ('topic', False), which is never updated, and propagates through to the check in "publish", where it is doomed to fail.

Unfortunately, I can see no easy solution to this but it can be mitigated by setting the '_connect_timeout' to 0.5 (_0.25 isn't accepted for some reason_).

I have attached the logs as they are quite difficult to read on-screen.

[TestLogs.txt](https://github.com/taverntesting/tavern/files/3560714/TestLogs.txt)

As an aside, "subscribing" is spelt incorrectly in the "not finished ... " message.

**Comment by michaelboulton** [comment]
I looked at wrapping subscriptions in a mutex to avoid this in https://github.com/taverntesting/tavern/pull/428 but I'm not sure if there might be some kind of deadlock that could occur there - could you see if that fixes the issue?

**Comment by KenStorey** [comment]
I have tried this with 0.30.0 + client.py from #428 and it seems fine.

I forced the 'mid' check in "_on_subscribe" to fail in order to test the other side of the fix and obtained results as previously described, i.e. multiple "not finished" messages culminating in "publishing anyway", just as I would expect.

No deadlocks encountered.

An elegant solution - and I got to learn about RLocks!
