### ISSUE TITLE
Checking response headers

### ISSUE THREAD

**Issue by harshabugg** [taverntesting/tavern#434]
Hi,
The following is not working for me:

response:
..headers: !anything

I am also not able to log headers into a file using "function", the way it can be done for body:

response:
..headers:
....$ext:
.......function: tavern_utils:save_header

If I need to check for headers in response I have to specify each field in the header, for eg:

response:
..headers:
....content-type: <some data>
....date: !anything 

etc...........

How can I check for headers in responses using !anything directive without specifying the the fields and how I use a function to dump all the response headers into a file?

**Comment by michaelboulton** [comment]
If you want to check for specific headers then you need to use `!anything` (or `!anystr`) with each header. If you want to check for specific headers then you can use the new `verify_response_with` block instead https://tavern.readthedocs.io/en/latest/basics.html#checking-the-response-using-external-functions
