### ISSUE TITLE
How to verify One item from response body (list)?

### ISSUE THREAD

**Issue by gbhangale416** [taverntesting/tavern#437]
Response :- 
{

    "post code": "110001",
    "country": "India",
    "country abbreviation": "IN",
    "places": [ 

        {
            "place name": "Janpath",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {

            "place name": "Rail Bhawan",
            "state": "New Delhi",
            "state abbreviation": "DL"

        },
        {
            "place name": "Connaught Place",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {
            "place name": "Eastern Court",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {
            "place name": "Parliament House",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {
            "place name": "Parliament Street H O",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {
            "place name": "Laxminarain Mandir",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {
            "place name": "New Delhi G P O",
            "state": "New Delhi",
            "state abbreviation": "DL"
        },
        {
            "place name": "Shastri Bhawan",
            "state": "New Delhi",
            "state abbreviation": "DL",
        }
    ]
}

and i want to verify that last `"place name": "Shastri Bhawan"`.

**Comment by scotchneat** [comment]
I'm still learning the capabilities of Tavern, but my first thought is you probably want to call an external function to loop through the items in the response property.

**Comment by michaelboulton** [comment]
You can use an external function as mentioned above, otherwise using strict: false will allow this in 1.0 https://github.com/taverntesting/tavern/issues/133
