### ISSUE TITLE
run function docstring vs documentation

### ISSUE THREAD

**Issue by bobhaffner** [taverntesting/tavern#447]
Hi,

Thank you so much for this wonderful tool.  

I noticed an inconsistency between the run() docstring and the docs.  The docs appear to be correct based on what I've seen.

From the [docstring](https://github.com/taverntesting/tavern/blob/238f6bd1ee65cf0d9ee7f3e590c9f4da0c0b6947/tavern/core.py#L347) 

```
Returns:
        bool: False if there were test failures, True otherwise
```

From the [docs](https://tavern.readthedocs.io/en/latest/basics.html#using-the-run-function)

> At the time of writing, this means it will return a 0 if all tests are successful, and a nonzero result if one or more tests failed (or there was some other error while running or collecting the tests).

**Comment by michaelboulton** [comment]
Thanks for spotting that, I've fixed it in the code (but probably won't put out a release just for that change)
