### ISSUE TITLE
[question]: how to add a delay or sleep between two stages?

### ISSUE THREAD

**Issue by tommyjcarpenter** [taverntesting/tavern#449]
If I have an API endpoint that takes a few seconds to do something, how do I hit that, add a sleep/delay, then perform another test? currently I have these both in a stages list, just want to add a delay between them.

**Comment by KenStorey** [comment]
**delay_before** or **delay_after**

[https://tavern.readthedocs.io/en/latest/basics.html#adding-a-delay-between-tests](url)

**Comment by tommyjcarpenter** [comment]
Thank you! I was searching for sleep, wait, etc, sorry!
