### ISSUE TITLE
[Question] How can allow my tests to have access to a dictionary of config variables?

### ISSUE THREAD

**Issue by mccasey** [taverntesting/tavern#453]
I would like to pass a dictionary returned from a private library that generates a dictionary of variables based on the env. Which contain a bunch of base urls and other stuff for a number of APIs I would like to test.

The tavern documentation allows for including a yaml file for variables to use in your tests, but is there a ways to just pass a dictionary of variables to tavern for my tests to have access to without having to dump it in a yaml file?

**Comment by mccasey** [comment]
I settle on using the `pytest_tavern_beta_before_every_test_run` hook.
```python
def pytest_tavern_beta_before_every_test_run(test_dict, variables):
    variables.update({ "config": app_configs })
```

**Comment by michaelboulton** [comment]
If you're generating some values from a library and then calling your tests with those, another way of doing this is passing configuration directly into the `run` entry point https://tavern.readthedocs.io/en/latest/basics.html#using-the-run-function . This depends on how you're starting your test run though, if you're calling pytest from the command line then your approach is more suitable.
