### ISSUE TITLE
How do I capture the return value from an external python function 

### ISSUE THREAD

**Issue by truptikant** [taverntesting/tavern#463]
When I use an external python function, I am able to pass the argument. But how do I capture the return value from the external function

**Comment by michaelboulton** [comment]
Can you give an example of something you're trying to do with the return value?

**Comment by truptikant** [comment]
I want to pass the whole response payload to an external python script,  filter out some values in the python script, return those values in a list to first tavern script, run a loop with the list elements in the tavern test.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by michaelboulton** [comment]
'running a loop' on the result implies that you are creating more tests while you are running a test, which is impossible in Pytest.
