### ISSUE TITLE
Does Tavern Support Kerberos Authentication??

### ISSUE THREAD

**Issue by scant22** [taverntesting/tavern#467]
I've been trying to perform a get request with kerberos authentication to pass along a lpta token from the login stage.  Currently, i'm able to get access to the token through python (as shown below) but am unsure of how I can pass it along this to tavern. 

<img width="1015" alt="Screen Shot 2019-10-22 at 5 34 09 PM" src="https://user-images.githubusercontent.com/56896005/67335713-32059380-f4f2-11e9-86dd-6de41265e087.png">

Is it's possible to do the same thing within tavern? Can I simply copy and paste over the token returned from my python request into my tavern yaml script under a cookie: heading? Or, can I run an external python function within tavern to return the token that way. 

Is kerberos authentication supported at all with tavern? Any and all help would be greatly appreciated.

Thanks!

**Comment by michaelboulton** [comment]
You can use a custom auth header with a fixture/external function but I don't really know the details of how kerberos authentication works. It might be possible to add in 'natively' but it's not a high priority at this time
