### ISSUE TITLE
calling external functions which are defined in class

### ISSUE THREAD

**Issue by SandeepNV** [taverntesting/tavern#471]
I have some external functions in a .py file which are defined under a class. I would like to use them in tavern module.

Can some one point me the right sytax of using $ext in a way that the method should get called along with its class name.

**Comment by Keri753951** [comment]
could someone also share it show to use it in windows

**Comment by SandeepNV** [comment]
Hello, can someone help me to resolve this.

**Comment by justin-fay** [comment]
Can you clarify what you mean by functions defined under a class, do you mean a method? If so you probably need  to instantiate the class before you call the methods which I don't think can be done from within tavern. What you can probably do is create a wrapper function which instantiates the class, calls the methods on it and returns the result. Example
file: util.py
```
def my_util_function():
    instance = MyClass()
    result = instance.my_method()
    return box.Box({'result': result})
```

This is used in the usual way from tavern.
```
    $ext:
      function: util:my_util_function
```

**Comment by michaelboulton** [comment]
The way described above is the only way to do it, Tavern will just call a function and it can't instantiate a class before that (eg, what if it has constructor arguments? How would it know what to pass?).
