### ISSUE TITLE
calling external functions in windows

### ISSUE THREAD

**Issue by Keri753951** [taverntesting/tavern#472]
Could someone share how to use external functions in windows?

Here is the path setup in linux
$ PYTHONPATH=$PYTHONPATH:tests py.test tests/

How to set the path in windows?
If the test.py and test.tavern.yaml are placed in D:\A\B folder

**Comment by Keri753951** [comment]
can someone help on this or tarven.yaml only support linux?

**Comment by michaelboulton** [comment]
Tavern does support Windows (there are definitely people using it on Windows) but I think the environment variables work differently on it. I wouldn't really know how to do it - I think it may also work differenly between a 'cmd' terminal and powershell
