### ISSUE TITLE
Support for providing custom content type for files

### ISSUE THREAD

**Issue by justin-fay** [taverntesting/tavern#473]
When sending multipart HTTP requests with `requests` you can specify a custom content type for each part of the multipart request.

```
files = {'file': ('report.xls', open('report.xls', 'rb'), 'application/vnd.ms-excel')}
>>> r = requests.post(url, files=files)
```
This is sometimes needed when a custom content type is required by an API eg. 
> 'application/vnd+vendorspecific+xml'. 

Tavern only supports the content type header for files as guessed by the `mimetyoes.guess_type` function.

```
    files:
        file_name: /path/to/file
```

A possibility for this could be to replace the path to the file with a two element list, where the second element is the header, the default case should still be supported and work as normal.
```
    files:
         file_name: [/path/to/file, apllication/custom]
         file_name_2: /path/to/file2
```

I am happy to give this a go myself if it is a desired feature.

**Comment by michaelboulton** [comment]
https://github.com/taverntesting/tavern/pull/485 Would this do what you need it to do?

**Comment by justin-fay** [comment]
Thank you @michaelboulton this fits my need perfectly.
