### ISSUE TITLE
collection failure for expected result with unicode character

### ISSUE THREAD

**Issue by Meyy1180** [taverntesting/tavern#475]
Operation system : Windows 7 Enterprise
Python Version : 3.6.7

getting following collection error when non english characters are present in the expected result 

c:\users\XXl\appdata\local\programs\python\python36-32\lib\codecs.py:321: in decode (result, consumed) = self._buffer_decode(data, self.errors, final) E UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 5827: invalid start byte

**Comment by michaelboulton** [comment]
Can you paste the whole error traceback? It might be an issue in Pytest rather than Tavern
