### ISSUE TITLE
How to get interpolated variables to stay dictionaries instead of being coerced into strings?

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#478]
Two dictionaries are loaded from fixtures in conftest.py:
tmp_author_alias_a and tmp_author_alias_b.

They are same structure with differing values:

```python
@pytest.fixture
def tmp_author_alias_a():
    return {
               "first_name": "Patrick",
               "last_name": "Neve",
# . . .
               "author_id": "dcfab002-d02f-4895-9557-b55f304af92d",
               "id": "ea36f093-1cae-403b-9c6e-3fe18b617221"
           }
```
They appear in the tavern script in - usefixtures:

```yaml
  - usefixtures:
      - encode_web_token
      - conjure_uuid
      - conjure_uuid_2
      - tmp_author_alias_a
      - tmp_author_alias_b
```
They need to be in the request json as list of dictionaries.

Entered this way:
```yaml
          authors: 
            - {tmp_author_alias_a}
            - {tmp_author_alias_b}
```
throws BadSchemaError: cannot define an empty value in test . . .

This way:
```yaml
          authors: 
            - "{tmp_author_alias_a}"
            - "{tmp_author_alias_b}"

In line 39 dict_util.py format_keys the list is pulled in as a node_class:
```
    formatted = val  # node_class: ['temp_author_alias_a', 'temp_author_alias_b']
    box_vars = Box(variables)
```
That is as a list of strings.
Each is then sent back through format_keys() (in line 48)
```
        formatted = [format_keys(item, box_vars) for item in val]
```
 as a string into which the dict is interpolated (line 51-53)
```
    elif isinstance(val, (ustr, str)):
        try:
            formatted = val.format(**box_vars)
```
Any way to get the list of dictionaries into the request json?  

A nice poser for your afternoon diversion! ;-)

**Comment by pmneve** [comment]
Was hoping to (ab)use !include files a bit less.

**Comment by pmneve** [comment]
Managed a workaround (related to #372):

- captured relevant data from and a get and three posts using save:
- in the verification section of the fourth stage (a post) called a function that
    - loaded a template json file into python object
    - extracted the needed dynamic data from the saved data
    - inserted that data into the python object and json.dump to a file
- in the POST for the target (metadata for an article) called $ext: to open the file and return with json.load

This got everything into the request body in a nice json format without coerced strings and the POST worked as expected.

If anyone wants to see (hold your nose) what I did please ping me at pneve@bepress.com and I'll put a gist together.

**Comment by pmneve** [comment]
Closing this as I've got it working within the tavern ecosystem.

**Comment by michaelboulton** [comment]
@pmneve I added an initial implementation of something like this in https://github.com/taverntesting/tavern/pull/486 , you should be able to use the `!force_format_include` tag to make it include a dict/list directly rather than coercing it to a string. it still requires wrapping it in a format string (see example https://github.com/taverntesting/tavern/pull/486/files#diff-d6f767251f45322e1be0a91893198c2a ) because it does still just reuse Python string formatting but just stops before it coerces it to a string.

It's not really tested at all at the moment so YMMV

**Comment by pmneve** [comment]
Super!  I'll give it a spin as soon as I can.

**Comment by michaelboulton** [comment]
Done in 0.34.0 https://tavern.readthedocs.io/en/latest/basics.html#including-raw-json-data

**Comment by pmneve** [comment]
@michaelboulton  #478 is a very good addition but unfortunately doesn't allow inclusion of an external file.
`    request:
      url: "{host}/{api_ver}/works/"
      method: POST
      json: !force_format_include ../../data/works/genned_work_payload_5850-002.json
`
fails with 
`        if field_name is None:
            raise exceptions.InvalidFormattedJsonError(
>               "Invalid string used for {}".format(yaml_tag)
            )
E           tavern.util.exceptions.InvalidFormattedJsonError: Invalid string used for !force_format_include

_          = '../../data/works/genned_work_payload_5850-002.json'
`
I'll continue with my workaround ext function to load json directly.
Still have to generate the json payload files at the moment:
`    response:
      status_code: 200
      headers:
        content-type: "application/json"
      save:
        body:
          author_B: data
      verify_response_with:
        - function: cleanup.cleanup:capture_for_cleanup
        - function: api_helpers:build_work_payload
          extra_kwargs:
            author_a: "{author_A}"
            disciplines: "{disciplines_a}"
            owner_uuid: "{conjure_uuid_2}"
            stage: "BP-5850-002B"
            api: "{api_ver}"

`
Then read it in like this:
`      json:
        $ext:
          function: api_helpers:load_json_file
          extra_kwargs:
            file_name: "genned_work_payload_5850-002.json"
            path_frag: "data/works"
            stage: "BP-5850-002D"
            api: "{api_ver}"
`
with this method:
`def load_json_file(**kwargs):
    api, stage = confirm_stage_and_api_ver(**kwargs)
    file_name = key_in_kwargs("file_name", **kwargs)
    logger.info(f"====>{whoami()[0]} : {file_name} {stage} {api} from {whoisparent()}")
    path_frag = key_in_kwargs("path_frag", **kwargs)
    file_spec = os.path.join(os.path.dirname(os.path.abspath(__file__)), path_frag, file_name)

    with open(file_spec, 'r') as fd:
        my_json = json.load(fd)
    return my_json
`
Very much appreciate your quick response to questions/requests/issues.   It's refreshing!
Thank you!

**Comment by michaelboulton** [comment]
I meant to reopen this earlier. I think the tag name was a bit incorrect, it was just meant to not format a string and having 'include' as part of the name was a bit misleading

**Comment by michaelboulton** [comment]
Going to open a separate issue to track changing the name of that tag (probably should have renamed it as part of 1.0), for reference the solution is
- If you need to include a whole file, use `!include`
- If you need to include a non-string , use a format variable with `!force_format_include`

**Comment by michaelboulton** [comment]
In 2.0 the tag will be called `force_original_structure`
