### ISSUE TITLE
Move extra_expected_keys behind a strict check

### ISSUE THREAD

**Issue by methsib** [taverntesting/tavern#482]
We have got a scenario where we want to verify certain items in list of dictionaries. It will be useful to have a feature which can verify one or few dictionaries out of many other in a list of dictionaries. 

Eg: 
Response body : [ {a=1, b=2, c=3}, {a=9, b=8, c=7}, {a=5, b=6, c=7}, {a=0, b=0, c=0} ]
Verify whether {a=1, b=2, c=3} in the list.

**Comment by michaelboulton** [comment]
This is due to https://github.com/taverntesting/tavern/issues/133
