### ISSUE TITLE
Auto deploying on tags

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#49]
- Set travis up to deploy to pypi on a new tag if all the tests pass.
- Possibly shuffle the travis CIs file around a bit so it runs a few less integration tests on a normal commit, but also runs the mqtt integration tests on a tagged commit
- Auto deploy a docker image as well when #48 is done

**Comment by benhowes** [comment]
See https://github.com/OverlockIoT/overlock-python/blob/master/.travis.yml for a working example of commit based deploy to pypi

**Comment by michaelboulton** [comment]
Done
