### ISSUE TITLE
Tavern Github Page example is out of sync with this page

### ISSUE THREAD

**Issue by hwangja** [taverntesting/tavern#503]
"Quickstart" section of this page has a bug - https://taverntesting.github.io/

2nd to last line has a "json" key, but fails Schema Validation. It's correct in the "Code" tab of this Git Repo: https://github.com/taverntesting/tavern

"json" key in the "Quickstart" should be "body"

**Comment by michaelboulton** [comment]
This is because the taverntesting.io page is in another repository and I wanted to make sure that it had the information for the 1.0 release in case I forgot to update it . This is technically a 'bug' but I'm going to leave it as it is  as the 1.0 release should happen soonish
