### ISSUE TITLE
Question: Any experience with using mocking with Tavern?

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#505]
Would like to get head start on automating new api by mocking requests/responses while using Tavern and pytest.

**Comment by michaelboulton** [comment]
You should be able to use a fixture (from your conftest.py, I don't think you'd even need it in the test itself) that spins up something like https://requests-mock.readthedocs.io/ , it might even be better to write the fake API using something simple like Flask so you can log all the requests then start/stop that flask server in the fixture .

**Comment by pmneve** [comment]
I'll definately look further into requests-mock and get to know Flask a bit better.
Thanks!
