### ISSUE TITLE
Valid JSON object generated by pytest fixture can't be used in Json field

### ISSUE THREAD

**Issue by oshabal** [taverntesting/tavern#512]
I have pytest fixture which return Json object into my test.
In test it looks like:
`...
marks:
    usefixtures:
         - test_json
...
json: "{test_json}" - API under test is saying that Json is invalid^ which is incorrect, because that same Json structure specified in test itself is working fine, but doesn't work if passed from a fixture.

**Comment by oshabal** [comment]
WARNING  tavern.util.dict_util:dict_util.py:55 Formatting 'test_json' will result in it being coerced to a string (it is a <class 'box.box.Box'>)

**Comment by michaelboulton** [comment]
As the error message says, things will be converted to a string if used as a variable. You can get around this by using the force_format_include tag as described in the documentation https://tavern.readthedocs.io/en/latest/basics.html#including-raw-json-data , but note that htis might change name to force_format in future (https://github.com/taverntesting/tavern/issues/478)
