### ISSUE TITLE
Question - How can we include a yaml file from different directory?

### ISSUE THREAD

**Issue by imkaka** [taverntesting/tavern#514]
In the same directory, it is possible to include via:
```yaml
includes:
  - !include data.yaml
```

How can we achieve the same if I want to import a file which resides in outer(root) directory?
```root/common.yaml  in  -> root/first/test_hola.tavern.yaml```

**Comment by benhowes** [comment]
Have you tried this?

```
includes:
  - !include ../data.yaml
```

**Comment by imkaka** [comment]
It worked 😃Thanks @benhowes  
I tried this some days back and It didn't work, maybe did something different at that time 😰. 

Closing the Issue!! 🎉
