### ISSUE TITLE
when using a variable in delay_after gives error

### ISSUE THREAD

**Issue by arjunrautela** [taverntesting/tavern#515]
I want to add delay after every stage and the value of delay is in a variable.yaml file. but when i execute the test using pytest i am getting the exception  
**tavern.util.exceptions.BadSchemaError: expected 'float-like' type at '/stages/0/delay_after', got '{sleep_time}'**
Is there a way to do it or can i set a default delay value in between every stage of my tests

**Comment by michaelboulton** [comment]
You can get around this by using the _float_ type token https://tavern.readthedocs.io/en/latest/basics.html#type-conversions like this:

```yaml
    delay_after: !float "{sleep_time}"
```

This is a bit unintuitive but it is just how it is curently implemented. This does need adding to the documentation.
