### ISSUE TITLE
cannot save dict item from a response which is a list

### ISSUE THREAD

**Issue by Bharati74** [taverntesting/tavern#517]
I have an API that returns a response as a list/array. I want to save 'attribute2', for an example, from the 2nd list item; I have tried mutlipe ways, but cannot find a solution. 
For an example: 
response is:
**[{'attribute1': 'FirstListItemAttr1', 'attribute2': 'FirstListItemAttr2'}, {'attribute1': '2ndListItemAttr1',  'attribute2': '2ndListItemAttr2'}]**

How do I save response for the value '2ndListItemAttr1'? Have tried many ways of: 
**response:
      status_code: 200
      save:
        body:
           - attr1: attribute1
           - attr2: attribute1**  
Thanks very much.

**Comment by michaelboulton** [comment]
I added an example here: https://github.com/taverntesting/tavern/blob/85b2668793059537d365c181b2838914cb1d709b/tests/integration/test_jmes.tavern.yaml#L145-L184

Basically I think  you want to do 

```yaml
save:
  body:
    attr1: "[0].atribute1"
    attr2: "[0].atribute2"
```

**Comment by Bharati74** [comment]
Michael, 

This worked! Greatly appreciate your prompt response. 

Thanks.
Bharati

**Comment by Bharati74** [comment]
Thanks very much fro your prompt response.

We are in the midst of deciding whether or not to use Tavern for our test
automation. This will help a lot, and I may have more questions in the
future. I am hoping to adopt Tavern for test automation.

Bharati
408-693-8875
