### ISSUE TITLE
Sending string and json in body

### ISSUE THREAD

**Issue by rizwansarwar** [taverntesting/tavern#520]
How do I send a combination of string and some json in request body. 

For example, I need to send the following.

`format=json&operation=triggerevent&oprdata={"name": "action", "user": -1, "events": {"list":[]}}
`
The stuff after oprdata= is valid json that can be very large, so I want to have it included externally. I have tried use !include with data but that does not work. Any help is appreciated. 

/Riz

**Comment by michaelboulton** [comment]
This isn't possible , you would need to use an external function or something to load that JSON yourself. From some experimentation it seems like trying to include json in the 'data' key is just converted to form data by Requests anyway.

This isn't really a supported use case for Tavern, so I don't think it will ever be supported, sorry.

**Comment by rizwansarwar** [comment]
Yes that is what I figured in the end would be case as this is a very edge case scenario.  From what I read in the documentation, it is not really possible to use $ext under requests? I am ok to write a python module to build the data to sent as body, but how do I pass it to data key under request block?
