### ISSUE TITLE
How do I log API Request and Response including headers?

### ISSUE THREAD

**Issue by rizwansarwar** [taverntesting/tavern#523]
I have been using Tavern for my testing and it works well. The problem is that when I want to just inspect the API request made and response sent from the server, I can't find a way to log that clearly via Tavern. Is there a way to set up Tavern to explicitly log API Request and/or Response calls when needed?

**Comment by oliver-hasse** [comment]
Have you seen the corresponding section in the documentation? https://tavern.readthedocs.io/en/latest/debugging.html

**Comment by michaelboulton** [comment]
I've added another hook in https://github.com/taverntesting/tavern/pull/615 (when it's merged) which will be called before each request which can be used to log the request arguments. There is already a hook for logging each response which can be used to log the response: https://tavern.readthedocs.io/en/latest/basics.html#hooks
