### ISSUE TITLE
Is it possible for tavern to pick up custom mqtt backend without cli arg?

### ISSUE THREAD

**Issue by burritoIand** [taverntesting/tavern#526]
I have a custom mqtt plugin and defined it in `setup.cfg` like so:
```
[options]
packages = find:
package_dir =
    = src
include_package_data = True

[options.packages.find]
exclude =
    tests

[options.entry_points]
tavern_mqtt =
    aws-mqtt = tavern_awsmqtt.plugin.mqtt.entry
```
I can only get it to work if I set the mqtt backend in cli argument. Is it possible for tavern to pick this up without that?
```
pytest --tavern-mqtt-backend aws-mqtt
```
Thanks!

**Comment by michaelboulton** [comment]
You should be able to use the `tavern-mqtt-backend` option in pytest.ini of the project you're testing as well, ie
```ini
tavern-mqtt-backend = aws-mqtt
```

**Comment by burritoIand** [comment]
thanks!
