### ISSUE TITLE
Is it possible to generate some parameters  at the time of the test ?

### ISSUE THREAD

**Issue by ns-zsyed** [taverntesting/tavern#527]
I need to test  a REST API that takes start time and end time fields in the request. I would like to set the endtime to current time and start time to "current time - 1000 secs" at the time of the test. How can I achieve this with tavern. Can it be done through hooks or fixtures.

**Comment by ns-zsyed** [comment]
Or is it possible to call a function with in marks:parametrize ?

**Comment by michaelboulton** [comment]
You should be able to do it with a fixture like this:

```python
import datetime
import pytest

@pytest.fixture
def get_negative_time():
    return (datetime.datetime.now() - datetime.timedelta(seconds=1000)).isoformat()
```

Note that I haven't test that this works but it should at least give you the right idea.
