### ISSUE TITLE
How to disable using persisted connection in `requests.Session`?

### ISSUE THREAD

**Issue by zhaoyi0113** [taverntesting/tavern#528]
I see `tavern` uses `requests.Session` to create a persisted connection within a connection pool. It producers a lot random errors relate to `connection closed`, `abort connection` etc. Is there a way to disable using persisted connection? Create a handshake for every connection. I don't mind if it gives a bad performance

**Comment by michaelboulton** [comment]
There isn't a way to disable the connection pooling, the way the internals are designed are that each test has a persistent internal session.

for what it's worth, having random connection closed/aborted issues seems like an issue with the server you're trying to connect to.

**Comment by zhaoyi0113** [comment]
Does this mean `Tavern` can't work with the server who doesn't support keep-alive?
