### ISSUE TITLE
Wrong context of terminal report if using fixture in stage

### ISSUE THREAD

**Issue by Bujyu** [taverntesting/tavern#533]
Hello, 

Recently i use tavern to test / debug our product API,
found the context of terminal report will be wrong at following case ...
(Running with option "--tavern-beta-new-traceback")

```
root
|-- conftest.py (has fixture "setup" which returns string "aaa")
|-- test_a.yaml (use fixture "setup" in "root/conftest.py")
`-- subdir
     |-- contest.py (has fixture "setup" which returns  string "bbb")
     `-- test_b.yaml (use fixture "setup" in "root/subdir/conftest.py")
```

The order of test will be "test_a.yaml" first, then "test_b.yaml" in my environment. 
(tavern 0.33.0 + pytest 4.5.0 with "--tavern-beta-new-traceback", also can reproduce on tavern 1.0.0a3 + pytest 5.3.5)

The context of terminal report about "test_a.yaml" will be wrong if test_a.yaml failed. 
(The context relating to fixture "setup" will be "bbb", not "aaa" as expected)

Anyone has any idea about this behavior?

**Comment by michaelboulton** [comment]
There was some strange behaviour with variables being carried between tests but I thought it had been fixed. This is the function where it gets the keys to format https://github.com/taverntesting/tavern/blob/3efff50c17d50956106ceaef2de0557a4b086c1a/tavern/testutils/pytesthook/error.py#L20-L36 for reference

**Comment by michaelboulton** [comment]
I'm actually unable to recreate this, see the `533-fixture-context-in-traceback` branch, can you still replicate it with the latest version?

**Comment by Bujyu** [comment]
> I'm actually unable to recreate this, see the `533-fixture-context-in-traceback` branch, can you still replicate it with the latest version?

Sorry for replying late ...

Test on tavern-1.0.0 (the latest version on pypi, with pytest 5.4.1), can not reproduce this issue.

Thanks for your effort!
