### ISSUE TITLE
Pytest Deprecation Warnings

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#540]
Pytest is now issuing the following Deprecation Warnings:

platform linux -- Python 3.7.5, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /usr/local/bin/python

/usr/local/lib/python3.7/site-packages/tavern/testutils/pytesthook/hooks.py:83
  /usr/local/lib/python3.7/site-packages/tavern/testutils/pytesthook/hooks.py:83: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

/usr/local/lib/python3.7/site-packages/tavern/testutils/pytesthook/file.py:233
  /usr/local/lib/python3.7/site-packages/tavern/testutils/pytesthook/file.py:233: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item = YamlItem(test_spec["test_name"], self, test_spec, self.fspath)

I believe this was introduced in pytest-5.4.0.

**Comment by michaelboulton** [comment]
Pytest 5.3 doesn't have from_parent (so I would need to pin the pytest dependency to pytest>=5.4), and changing it to use from_parent breaks fixtures, so I'm not going to fix this until Pytest starts actually breaking tests again.

**Comment by montanaflynn** [comment]
I used:

`pip3 install 'pytest<5.4' 'tavern'`

Which installs pytest `pytest-5.3.5` as of today.

**Comment by michaelboulton** [comment]
https://github.com/taverntesting/tavern/issues/575 now broken in pytest 6
