### ISSUE TITLE
Response status code checking always raises warning

### ISSUE THREAD

**Issue by darth-llamah** [taverntesting/tavern#541]
Changes introduced in tavern/_plugins/rest/response.py in 1.0.0 release make Tavern to always raise warning when checking rest response status code- it is not possible to check in `requests.status_codes.codes` as it always returns False
Possible solution:
* status codes should be checked in `requests.status_codes._codes` as it was implemented before 1.0.0

**Comment by chrisinmtown** [comment]
Using version 1.0.0 I see the following during test execution, is this what the issue is about?

`WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'`

**Comment by darth-llamah** [comment]
Yes, this is the issue. It's not critical but those warnings should not occur
