### ISSUE TITLE
Saving response with correct format... trying to use it in other stage... empty

### ISSUE THREAD

**Issue by rebecca-makar** [taverntesting/tavern#542]
I just recently updated to 1.0.0

I was saving a response in an anchor stage. Then that anchor was used throughout other steps, and the saved response was used in the next stage of the test. It seems that even though I am saving the response it is bringing in an empty string. 

I had issues first getting the correct new format, but once I figured that out it seemed to be correct. Now issue is reusing that var.

**Comment by michaelboulton** [comment]
Can you give a code snippet of what you're trying to do? If it is empty then that implies that it did save something but it saved an empty string. If it wasn't saving anything then it would just raise an error.

**Comment by rebecca-makar** [comment]
So my coworker and I figured out the issue, it is a way jmes needs dashes to be escaped: https://github.com/jmespath/jmespath.py/issues/109

what worked for us: singlequote doublequote <> doublequote singlequote
headers:
        Header-With-Dash: !anything
      save:
        headers:
          thing_being_saved: '"Header-With-Dash"'
