### ISSUE TITLE
Test Ordering

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#544]
I can't work out how Tavern decides what order to run tests in.

I would like to ensure that one particular test in a suite, consisting of numerous .tavern.yaml files, is always run before any others.

Is this possible?

**Comment by michaelboulton** [comment]
It runs in whatever order Pytest decides to run them in, I don't think there's any particular way to control it without directly interfacing with it. Perhaps override this hook https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_collection_modifyitems and put your test first in the list?
