### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#55]
Number of total stages (not just tests), time for each request, etc.

**Comment by michaelboulton** [comment]
Along with #2 , probably need to come up with an output log format to make this nice to use

**Comment by bitdivision** [comment]
Dependent on hooks

**Comment by michaelboulton** [comment]
This is now exported by the Allure test reports https://tavern.readthedocs.io/en/latest/basics.html#generating-test-reports - any further info can be scraped from those reports
