### ISSUE TITLE
how to set tavern-merge-ext-function-values ?

### ISSUE THREAD

**Issue by 13242084001** [taverntesting/tavern#557]
forexample：
 how to set tavern-merge-ext-function-values options?

**Comment by michaelboulton** [comment]
You can pass it on the command line like `pytest --tavern-merge-ext-function-values ...` or in pytest.ini like
```ini
[pytest]
tavern-merge-ext-function-values = true
```

**Comment by lucidity-joe** [comment]
@michaelboulton I've found for myself that only passing it in to the command line works. I have:

`[pytest]
tavern-merge-ext-function-values = true`

but it doesn't work at all

**Comment by mcasado** [comment]
This is the way that some of the tavern configs work form me in pytest.ini
# content of pytest.ini
[pytest]
addopts = --tavern-merge-ext-function-values --tavern-use-default-traceback --html=report.html --self-contained-html -vv
tavern-strict = json:off headers:off
