### ISSUE TITLE
max_retries parameter is not taking tavern environment variable

### ISSUE THREAD

**Issue by truptikant** [taverntesting/tavern#559]
Earlier (working)
max_retries: 10
----

now trying to implement env var --( giving error error)
max_retries: !int "{tavern.env_vars.MAX_RETRY_TESTS}"
SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Value '<tavern.util.loader.IntToken object at 0x110043310>' is not of type 'int'. Path: '/stages/0/max_retries'.

Similar way !int "{tavern.env_vars.MAX_RETRY_TESTS}" works fine for status_code param under response field. 

Can someone please look into this. Am I missing something here ?

**Comment by michaelboulton** [comment]
What version are you using? this is supported and there is an integration test for it :
https://github.com/taverntesting/tavern/blob/04a100b59449be33d160c92b858155700f769765/tests/integration/test_retry.tavern.yaml#L41-L55
This should also work with environment variables
