### ISSUE TITLE
Validate a JSON list of arbitrary length with strict objects

### ISSUE THREAD

**Issue by dfego** [taverntesting/tavern#568]
I've got an API that returns a list of JSON objects that I want to validate all match a specific schema, i.e. have the same keys and types, but the list itself can be of arbitrary length. My understanding is that right now my only option is to write an external function, is that right?

I'm not sure if this is a difficult feature or one that would be useful to anyone else, but I've used Tavern a few times over the last couple of years and this has come up each time in my use cases. In other words, I want to match:

```yaml
      json:
        - key1: !anystr
          key2: !anystr
          key3: !anybool
```

And I want it to match that list of any length (which `strict off` will do), but ensure that _all_ the contained list items match. Based on some quick testing, `strict off` will pass if any item matches, and it literally ignores whatever else is there. And this behavior makes sense with homogenous, non-object list items, but less sense here.

So consider this a feature request if there isn't already a way (other than external functions) to do this!

**Comment by michaelboulton** [comment]
You should be able to do it with the validate_pykwalify builtin function, example: https://github.com/taverntesting/tavern/blob/master/tests/integration/test_validate_pykwalify.tavern.yaml , if you want to use any other kind of validation library you will need to use an external function though.

**Comment by dfego** [comment]
Thanks for pointing this out, this looks exactly like what I need! Was there somewhere I should have seen this in the documentation? If not, it might be worthwhile to add, perhaps while discussing the strict options, or nearby.

**Comment by michaelboulton** [comment]
It's not really documented very well, I think the only thing that needs fixing for a '2.0' release is locking down the API an documenting exactly what is available
