### ISSUE TITLE
help using variables or external functions to construct urls per test

### ISSUE THREAD

**Issue by dotorg-richard** [taverntesting/tavern#569]
I want to avoid hard-coding the urls for tests so they work for everyone across different environments with different url components(hostname, port, paths) which I'm sure is a common requirement, however the problem I have is that each developer's local and remote environment will differ so I want to populate these variables from code for each test (each developer and environment maintains their own config file, so this is possible.)

Example url requirements:
```
test_service_1 **on my machine**:
 local env: localhost:3001/local/service_1 
 remote env: richard.api.company.com/service_1 

test_service_2 **on my machine**:
 local env: localhost:3002/local/service_2 
 remote env: richard.api.company.com/service_2 

test_service_1 **on developer_x machine**:
 local env: localhost:3002/local/service_1 
 remote env: developer_x.api.company.com/service_1 

test_service_2 **on developer_x machine**:
 local env: localhost:3001/local/service_2
 remote env: developer_x.api.company.com/service_2
```

so the structure I need for a url is {protocol}://{host}{port}/{prefix}{path} where port and prefix can be blank and where each variable could be different based on a combination of test file, environment and developer.

I've studied the docs and attempted to find a solution but to no avail, the main problem is that external functions won't take a parameter, then the url must be returned as a single string and overwrites the variable entirely, so I also cannot return a partial url from a function and then parse/prefix/append the string as needed per test based on other external parameters.

I'd rather not rely on environment variables and have developers maintain hundreds of environment variables just to support this requirement when all that configuration data is already maintained in everyone's .env file and injected in the the application's config.  Is there a workaround I'm not seeing that doesn't require tons of code duplication in every test just to construct the right url every time?

**Comment by michaelboulton** [comment]
I think the only real solution to this is to reuse pytest autouse fixtures (I did start a PR for this actually https://github.com/taverntesting/tavern/pull/562/files ) and then just write a separate fixture for each 'part' of the URL which can then be combined as you want. At the moment what you want is possible but obviously very complicated, as you say.

**Comment by michaelboulton** [comment]
Autouse fixtures are in now, so using an autouse fixture is probably the best solution to this (ie, write a fixture to load those variables from the environment and just use them in each test)
