### ISSUE TITLE
Disabling a test dynamically using `skip if` with environment variables

### ISSUE THREAD

**Issue by elsbrock** [taverntesting/tavern#570]
I am looking for a way to disable a test dynamically, depending on the presence of an environment variable.

We have an environment variable indicating the context such as `dev` or `prod`, and would like to enable or disable certain tests (because they test features that are only applicable in either context).

I have found `skip if` and have tried to make use of `tavern.env_vars`, but I am getting key errors, so I am assuming that object is not available in this context. Is there another way to achieve this?

**Comment by michaelboulton** [comment]
Fixed in 1.5.0

**Comment by elsbrock** [comment]
Thank you!
