### ISSUE TITLE
ERROR collecting test session - Plz suggest the fix

### ISSUE THREAD

**Issue by greeshmavyas** [taverntesting/tavern#575]
+ set -e
+ cd /usr/bin
+ PYTHONPATH=.
+ pytest -s -vv --tb=short -rpPfEs ./test_inapp.create_notifications.tavern.yaml ./test_inapp.query_notifications.tavern.yaml
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /usr/bin
plugins: tavern-1.2.2
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
../local/lib/python3.8/dist-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../local/lib/python3.8/dist-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../local/lib/python3.8/dist-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:43: in pytest_collect_file
    return YamlFile(path, parent)
../local/lib/python3.8/dist-packages/_pytest/nodes.py:95: in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
E   pytest.PytestDeprecationWarning: Direct construction of YamlFile has been deprecated, please use YamlFile.from_parent.
E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
=========================== short test summary info ============================
ERROR  - pytest.PytestDeprecationWarning: Direct construction of YamlFile has...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.39s ===============================

**Comment by michaelboulton** [comment]
This is 'fixed' in 1.2.3 by locking to pytest<6, will reopen the old ticket about from_parent

**Comment by burritoIand** [comment]
.. build started failing bc it used pytest > 6, is this temporary?
