### ISSUE TITLE
Pylint==2.4.4 has been marked as insecure by pyup.io

### ISSUE THREAD

**Issue by dankarpinski** [taverntesting/tavern#578]
Pylint==2.4.4 used by tavern is marked as insecure on the pyup.io [safety db](https://github.com/pyupio/safety-db/blob/c4f4673861c540659b8995cf23af2915c584e9d3/data/insecure_full.json#L12673)

This means doing a `pipenv check` now gives the error:
```
38224: pylint <2.5.0 resolved (2.4.4 installed)!
Pylint 2.5.0 no longer allows ``python -m pylint ...`` to import user code. Previously, it added the current working directory as the first element of ``sys.path``. This opened up a potential security hole where ``pylint`` would import user level code as long as that code resided in modules having the same name as stdlib or pylint's own modules.
```

Is there a reason for pinning to `2.4.4`? As this prevents me upgrading

**Comment by michaelboulton** [comment]
Should be fixed in 1.2.4
