### ISSUE TITLE
PluginLoadError from mismatched requirements

### ISSUE THREAD

**Issue by zroger** [taverntesting/tavern#579]
Between `1.2.2` and `1.2.3` my test suite started raising this exception:

```
tavern.util.exceptions.PluginLoadError: Error loading plugin requests = 
tavern._plugins.rest.tavernhook:TavernRestPlugin - (PyYAML 5.3.1 (/var/task), Requirement.parse('PyYAML==5.3'))
```

I have an unpinned `PyYAML` requirement in my project which is how I ended up with version `5.3.1`, but tavern `1.2.3` wants exactly version `5.3`, which was pinned in #577. Digging through the code, it looks like the exception comes from stevedore because the [`verify_requirements`](https://github.com/taverntesting/tavern/blob/3efff50c17d50956106ceaef2de0557a4b086c1a/tavern/plugins.py#L113) argument is used when loading the plugins.

To get around this issue, I've pinned tavern to `1.2.2` rather than pinning PyYAML since `5.3.1` is a [security fix](https://github.com/yaml/pyyaml/pull/386).

I'm not sure how to proceed to fix this in the long run. The two options I can see are to give the PyYAML requirement a looser version specifier, or to remove the `verify_requirements` argument. If you let me know which you prefer, I can try to put together a patch.

**Comment by michaelboulton** [comment]
Should be fixed in 1.2.4
