### ISSUE TITLE
Build failing with latest 1.2.3

### ISSUE THREAD

**Issue by burritoIand** [taverntesting/tavern#581]
Hello, my ci/cd began to fail just now while running tests and it seems to be a problem installing packages with pip using tavern 1.2.3. I reverted to 1.2.2 and everything installs/passes fine.

error:
```
Failed to build PyYAML paho-mqtt docopt ruamel.yaml.clib wrapt lazy-object-proxy
ERROR: Could not build wheels for lazy-object-proxy which use PEP 517 and cannot be installed directly
```

pip 20.1
pytest latest (tried pytest<6)
python 3.8

also it looks like paho-mqtt is using a version from 2017 but not sure if that matters (my mqtt tests work fine)

**Comment by michaelboulton** [comment]
Should be fixed in 1.2.4
