### ISSUE TITLE
Use variables in the files section

### ISSUE THREAD

**Issue by SimonPicciotto** [taverntesting/tavern#597]
Hello, 
I'm trying to use a variable (defined in common.yaml) in the files section: 
  - name: upload file with dynamic name
    request:
      url: "{protocol:s}://{host}:{port}/upload"
      method: POST
      data:
        mime: audio-wav
      files:
          file: "{upload_directory}/{file_name}"
    response:
      status_code: 200

# common.yaml
---
Name: Common test information
variables:
  source_directory: c:/mycompany/files  
  file_name: ir_inter.wav 

But tavern does not catch the variables values, and i get a "file  "{upload_directory}/{file_name} not found" error

**Comment by KenStorey** [comment]
Firstly you have named your variable "source_directory", not "upload_directory".

Secondly, I think it should be written as file: "{upload_directory}"/"{file_name}".

**Comment by SimonPicciotto** [comment]
Hi, 
Thanks and my bad, you're right, its "source_directory" and not "upload_directory".
in my project i use the correct variable: 

name: upload file with dynamic name
request:
url: "{protocol:s}://{host}:{port}/upload"
method: POST
data:
mime: audio-wav
files:
file: "{source_directory}/{file_name}"
response:
status_code: 200


Name: Common test information
variables:
source_directory: c:/mycompany/files
file_name: ir_inter.wav

That being said, the syntax 
"{source_directory}"/"{file_name}" doesn't work either, I get a tavern.util.exceptions.BadSchemaError.

I tried 
name: upload file with dynamic name
request:
url: "{protocol:s}://{host}:{port}/upload"
method: POST
data:
mime: audio-wav
files:
file: "{source_directory}"/"{file_name}"
response:
status_code: 200

Any idea?

**Comment by michaelboulton** [comment]
I think this is the same as https://github.com/taverntesting/tavern/issues/551
