### ISSUE TITLE
Feature Request: Negative Testing

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#621]
It would be useful to have a mark, similar to xfail but on a per stage basis, which tells Tavern that the specified response is not expected.

For example, if I want to check that when a device is switched off it no longer sends data then I would write something like:
```
    mqtt_publish:
      topic: device/control
      json:
        set_state: "off"

    mqtt_response:
==>   occurs: false
      topic: device/output
      json:
        output: !anything
      timeout: 2
```

**Comment by michaelboulton** [comment]
I'm thinking this would be an mqtt-specific thing which would make it not too difficult to implement (ie, just wait and make sure it doesn't happen like in the example). I don't think there would be much use for a stage where you made a HTTP request and wanted to make sure it _doesn't_ return a 200, when you could just say that you _do_ expect a 400
