### ISSUE TITLE
Feature request: add possibility to use yaml anchors from different files.

### ISSUE THREAD

**Issue by EduardKuzhir** [taverntesting/tavern#629]
Documentation (part about Reusing requests and YAML fragments) says:
> This does not however work if there are different documents in the yaml file

Is it possible to make it work? I'd like to extract common requests into some 'library' yaml to make it possible to reuse.

**Comment by michaelboulton** [comment]
There is the concept of a 'document' in yaml, where multiple documents can be in one file, which is what the documentation is referring to (and it says a bit further down that you can actually reuse fragments in the same file even if they are in a separate document)

If you want to include something from a different file entirely, you can use the `!include` directive which will just load the contents of the file into wherever you include it: https://tavern.readthedocs.io/en/latest/basics.html#including-external-files

**Comment by EduardKuzhir** [comment]
I've tried to use such way to include YAML with anchors on request definition to reuse some requests but I failed to do it. As I see it's only possible to do it in single file?

**Comment by michaelboulton** [comment]
It is only possible in a single file, if you need to reuse requests then you need to use the `!include` tag as mentioned above.
