### ISSUE TITLE
How can I pass certain multiple files/images in a API request (body parameter)?

### ISSUE THREAD

**Issue by shreya-ruge** [taverntesting/tavern#636]
How can I pass certain multiple files/images in a API request (body parameter)?

We have tried parameterization (key:value).We want all images to be verified within same test ...not one by one
eg. I need to send images as below:

files:
img1: image1.jpg
img_set: image2.jpg, image10.jpg , image 15.png, image20.jpg...and so on

Is this possible using tavern?  Can someone help in this?

**Comment by michaelboulton** [comment]
What do you mean by passing multiple files at a time? Tavern sends the files in `multipart/form-data` where each field only has 1 file associated with it, there is no way to send multiple files per part

**Comment by SyntaxColoring** [comment]
> Tavern sends the files in multipart/form-data where each field only has 1 file associated with it, there is no way to send multiple files per part

I'm not sure if this is exactly what @shreya-ruge meant, but:

In `multipart/form-data`, you *can* upload multiple files into a single form field (like `img_set` in the example above). This is standard, and `requests` supports it, but it looks like the current YAML syntax is preventing it in Tavern. I've opened a new issue for this and fleshed it out a bit: #833
