### ISSUE TITLE
how to save response from list of dictionary if response like this ? I want to save data1 from first dictionary from list using tavern

### ISSUE THREAD

**Issue by Tinku9090** [taverntesting/tavern#641]
[
    {
        "data1": 2,
        "data2": "bbbbb",
        "data3": "cccc",
        "data4": 1,
        "data5": "Andersta gård",
        "data6": "aaaaa"
    },
    {
      
        "data1": 2,
        "data2": "bbbbb",
        "data3": "cccc",
        "data4": 1,
        "data5": "Andersta gård",
        "data6": "aaaaa"
    }
    
]

**Comment by sohoffice** [comment]
Perhaps you can try the below ?

```yaml
      save:
        json:
          data1: [0].data1
```
