### ISSUE TITLE
integrate pytest attributes

### ISSUE THREAD

**Issue by megetron** [taverntesting/tavern#66]
Hey,
Can you use pytest parameters when you run tavern-cli? 

Currently i would like to generate --junitxml file.

Thanks

**Comment by michaelboulton** [comment]
The tavern-ci command line tool doesn't use any of the pytest functionality. I noticed the documentation is a bit ambiguous (I'll update it now) but the best way of using tavern is via pytest so that you get all that extra functionality.

**Comment by megetron** [comment]
Cool. Can you also add documentation of how to run yaml file with pytest? Currently i get error that the yaml file not found:
ERROR: not found /home/me/test_a.tavern.yaml
(no name '/home/me/test_a.tavern.yaml' in any of [])

**Comment by michaelboulton** [comment]
I've updated that now at https://taverntesting.github.io/ along with more implicitly suggesting that Pytest is the better way of using it.

**Comment by michaelboulton** [comment]
Going to close this issue now the documentation is done. For future reference, we might switch to only using pytest in future, directly or indirectly
