### ISSUE TITLE
Tavern commands failed

### ISSUE THREAD

**Issue by virt12** [taverntesting/tavern#680]
I am running API testing in ubuntu, virtualbox. In hivemind environment, when hivemind server is running. I am using this command
tox -e tavern -- --workers auto --tests-per-worker auto --durations=0.
Link to project:https://gitlab.syncad.com/hive/hivemind.

 And I am getting this error:
================= 1 warning, 1460 errors in 216.34s (0:03:36) =================
ERROR: InvocationError for command /home/zymantas/Desktop/hivemind/.tox/tavern/bin/pytest --workers auto --tests-per-worker auto --durations=0 (exited with code 2)
___________________________________ summary ___________________________________
ERROR:   tavern: commands failed

How to resolve it?

**Comment by michaelboulton** [comment]
Does it happen if you run it without the extra pytest flags? If not, could you give a bit more of the error output? I'm not sure what the issue would be without more of the error message
