### ISSUE TITLE
Recent update of attrs package to 21.1.0 causes tests to fail

### ISSUE THREAD

**Issue by JakeLSaunders94** [taverntesting/tavern#685]
Hi, I started getting failures on CI this morning when running tavern tests, error is as follows:

```
__ ERROR collecting nautilus/functional_tests/test_oauth_app_api.tavern.yaml ___
venv/lib/python3.7/site-packages/tavern/testutils/pytesthook/file.py:317: in collect
    for i in self._generate_items(test_spec):
venv/lib/python3.7/site-packages/tavern/testutils/pytesthook/file.py:292: in _generate_items
    item.add_markers(pytest_marks)
venv/lib/python3.7/site-packages/tavern/testutils/pytesthook/item.py:94: in add_markers
    pm = attr.evolve(pm, mark=new_mark)
venv/lib/python3.7/site-packages/attr/_funcs.py:347: in evolve
    changes[init_name] = evolve(value, **changes[init_name])
E   TypeError: evolve() argument after ** must be a mapping, not Mark
```

There was a major release of attrs package this morning 06/05/2021, which appears to have caused a breaking change. Pinning this package to the previous version fixes the issue.

**Comment by JakeLSaunders94** [comment]
Apologies, this appears to be an issue with pytest, rather than tavern.

**Comment by TVenuMadhav** [comment]
Same issue here. Failed this morning

**Comment by michaelboulton** [comment]
https://www.attrs.org/en/stable/changelog.html#backward-incompatible-changes It looks like this has been fixed by the attrs package, so going to close this
