### ISSUE TITLE
Is there any plan to generate yaml testscript from Postman Fiddler Charles

### ISSUE THREAD

**Issue by dy20082250** [taverntesting/tavern#696]

**Comment by dy20082250** [comment]
because the yaml testscript is formatted,maybe we could make one code generator to generate testscript from Postman or from swagger's Interface document；it could improve the space of writing testscript

**Comment by prashantbarik** [comment]
@michaelboulton can it be done? As it will help so much testing areas.

**Comment by michaelboulton** [comment]
There isn't any plans to do this in future, as each of those tools do things in quite different ways to Tavern. For example, in Postman you can write a piece of Javascript to check the response, and there is no way for Tavern to parse and run that.

It may be possible to generate a postman collection from a tavern test, but it would miss a lot of the internal functionality  (such as checking JWTs, regexes, etc)
