### ISSUE TITLE
Is it possible to define parametrize from a response? 

### ISSUE THREAD

**Issue by giladlevy7** [taverntesting/tavern#698]
Hi,

I'm trying to do the following:

1. Create a test that will start by fetching a list of items from my API.
2. Iterate over the response with another stage/test.

Is it possible?
I couldn't find any way to define the parameterize to be dynamic and defined automatically from the response.

Thanks!
Gilad

**Comment by michaelboulton** [comment]
This isn't possible (and will probably never be) unfortunately as it requires creating tests at runtime which isn't possible with Pytest
