### ISSUE TITLE
AttributeError: 'YamlItem' object has no attribute 'obj'

### ISSUE THREAD

**Issue by megetron** [taverntesting/tavern#70]
Cant execute simple tests. Here is a stacktrace

  tests git:(master) ✗ python -m pytest -k  generator/v1_5/integrations/datasets/test_get_sources.tavern.yaml
==================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.12, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/guy/proj/api/tests, inifile:
plugins: tavern-0.2.5, pythonpath-0.7.2, pspec-0.0.3, ordering-0.5, hidecaptured-0.1.2, env-0.6.2, console-scripts-0.1.4, bdd-2.20.0, pyfakefs-3.3
collected 2 items / 5 errors                                                                                                                                                                 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 100, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 137, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 147, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 331, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pytest_pspec/plugin.py", line 35, in pytest_collection_modifyitems
INTERNALERROR>     node = item.obj
INTERNALERROR> AttributeError: 'YamlItem' object has no attribute 'obj'

================================================================================== 5 error in 0.60 seconds ===================================================================================

**Comment by michaelboulton** [comment]
Interesting that we managed to get an internal error in pytest, I'm guessing it's a conflict with one of the other plugins. Does it still happen if you upgrade to the latest version (0.7.4)? Can you also give an example of the simple test (or does this also happen with `test_minimal.tavern.yaml` from the README?

Do you have a list of the plugins you've installed or is it just those ones listed (pythonpath-0.7.2, pspec-0.0.3, ordering-0.5, hidecaptured-0.1.2, env-0.6.2, console-scripts-0.1.4, bdd-2.20.0, pyfakefs-3.3)

**Comment by michaelboulton** [comment]
I realised I was reading the traceback wrong and it's something in pytest_pspec - it seems like that plugin was designed to work only with python tests. It might be possible to fix it by making the 'docstring' of the test equal to the `test_name`

**Comment by michaelboulton** [comment]
@megetron This should be fixed in 0.7.5

**Comment by megetron** [comment]
Yes! It seems like upgrading version fixed it.
Also uninstall pytest_pspec solved the issue as well in the previous version. 


Thank you very much for the quick reply!

**Comment by michaelboulton** [comment]
No problem!
