### ISSUE TITLE
special json data INTERNALERROR

### ISSUE THREAD

**Issue by visonforcoding** [taverntesting/tavern#708]
```json
{
    "box_list": "[{\"length\":\"100\",\"width\":\"100\",\"height\":\"100\",\"weight\":\"10\",\"goods_sku_num\":\"\",\"goods_num_total\":\"\",\"isDisabled\":false,\"box_material\":\"纸箱\",\"goods_list\":[{\"goods_sku\":\"V1001\",\"goods_num\":10}]}]"
}
```
i use this json data request got a error
![image](https://user-images.githubusercontent.com/4387302/131971970-91437037-5655-4023-a2c1-6f161b9718dc.png)

**Comment by michaelboulton** [comment]
Can you please copy the entire error output, I can't tell what's happening based on the screenshot

**Comment by visonforcoding** [comment]
> Can you please copy the entire error output, I can't tell what's happening based on the screenshot

tests/_api/test_order-stock.tavern.yaml 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 126, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 217, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/skipping.py", line 272, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 337, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/reports.py", line 322, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/testutils/pytesthook/item.py", line 233, in repr_failure
INTERNALERROR>     attach_text(str(error), name="error_output")
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/testutils/pytesthook/error.py", line 219, in __str__
INTERNALERROR>     return self.longreprtext
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/testutils/pytesthook/error.py", line 214, in longreprtext
INTERNALERROR>     self.toterminal(tw)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/testutils/pytesthook/error.py", line 204, in toterminal
INTERNALERROR>     self._print_formatted_stage(tw, stage)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/testutils/pytesthook/error.py", line 153, in _print_formatted_stage
INTERNALERROR>     line = format_keys(line, keys)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/util/dict_util.py", line 118, in format_keys
INTERNALERROR>     formatted = _check_and_format_values(val, box_vars)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/tavern/util/dict_util.py", line 29, in _check_and_format_values
INTERNALERROR>     for (_, field_name, _, _) in would_format:
INTERNALERROR> ValueError: unmatched '{' in format spec


i guess ,it is json prase error

**Comment by michaelboulton** [comment]
I think this is because you are including curly braces in the string, which tavern then tries to format (and fails). I don't think there is an easy way to fix this because although there is the [`!raw` tag ](https://yaml.org/spec/1.2/spec.html#id2761292) which turns off formatting, there can only be one [yaml tag](https://yaml.org/spec/1.2/spec.html#id2761292) per line so you can't do `!raw !include create_order_data.json`.

You can change the content of the file to 

```
{
    "box_list": !raw "[{\"length\":\"100\",\"width\":\"100\",\"height\":\"100\",\"weight\":\"10\",\"goods_sku_num\":\"\",\"goods_num_total\":\"\",\"isDisabled\":false,\"box_material\":\"纸箱\",\"goods_list\":[{\"goods_sku\":\"V1001\",\"goods_num\":10}]}]"
}
```

And it should work, but then any other programs that try to read it will fail. Otherwise, you will have to just copy/paste the content of the file into the test and do 

```
stages:
  - name: oms下单

    request:
      url: "{oms_stg_env.base_url}/order/create"
      method: POST
      headers:
        test-token: "admin"
        Content-Type: application/json
      json:    
        box_list: !raw "[{\"length\":\"100\",\"width\":\"100\",\"height\":\"100\",\"weight\":\"10\",\"goods_sku_num\":\"\",\"goods_num_total\":\"\",\"isDisabled\":false,\"box_material\":\"纸箱\",\"goods_list\":[{\"goods_sku\":\"V1001\",\"goods_num\":10}]}]"

```
