### ISSUE TITLE
Logging example in the Tavern document does not work

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#712]
I'm attempting to set up Tavern logging, exactly as shown in the document [here](https://tavern.readthedocs.io/en/latest/debugging.html), however it throws an error:
```
     ImportError while loading conftest '/tavern_tests/conftest.py'.
tavern_tests/conftest.py:5: in <module>
    config.dictConfig(yaml.load(log_spec_file))
usr/local/lib/python3.9/logging/config.py:809: in dictConfig
    dictConfigClass(config).configure()
usr/local/lib/python3.9/logging/config.py:546: in configure
    raise ValueError('Unable to configure '
E   ValueError: Unable to configure formatter 'default'

```

**Comment by jaywon** [comment]
@KenStorey Ran into this today. You need to `pip install colorlog` which has the the referenced `handler` defined.

**Comment by KenStorey** [comment]
> @KenStorey Ran into this today. You need to `pip install colorlog` which has the the referenced `handler` defined.

Thank you. That did the trick.

**Comment by ashishpatel1992** [comment]
I am unable to print debug statements in console.
It only prints logs if request fails. 
Isn't the default behavior for `DEBUG` would be to print on console
