### ISSUE TITLE
Is it possible to have list in parametrize ?

### ISSUE THREAD

**Issue by delonleo** [taverntesting/tavern#731]
Got pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
Your help please ....

```
marks:
  - parametrize:
      key:
        - valid_field_1
        - valid_field_2
        - valid_field_3
      vals:
        - [
            "1",
            [
              "1",
              "2",
              "3",
            ],
            0,
          ]
        - [
            "2",
            [
              "1",
              "2",
              "3",
            ],
            0,
          ]

stages:
  - name: eg request
    request:
      method: POST
      json:
        field_1: "{valid_field_1}"
        field_2: "{valid_field_2}"
        field_3: !int "{valid_field_3}"
    response:
      status_code: 200
```

**Comment by KenStorey** [comment]
valid_field_2 appears twice in the keys and is used in the stage as both a list and an int.

I guess you mean valid_field_3?

**Comment by delonleo** [comment]
apologies, edited the examle. thank you.

**Comment by michaelboulton** [comment]
I have a working example of this in https://github.com/taverntesting/tavern/pull/746 but I need to think if this will break any existing behaviour. I'm not sure anyone will rely on the internal errors from Tavern so it should be fine though
