### ISSUE TITLE
Unable to use --tavern-strict flag to turn strictness off

### ISSUE THREAD

**Issue by hamx0r** [taverntesting/tavern#737]
Running ` pytest --tavern-strict json:off ` results in 

```
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: argument --tavern-strict: invalid choice: 'json:off' (choose from 'json', 'headers', 'redirect_query_params')
```

Expected result: `json:off` is an accepted value and results in all JSON comparisons in Responses to only compare the subset provided in the test.

**Comment by michaelboulton** [comment]
Fixed in 1.17.2
