### ISSUE TITLE
Is blocking of pytest 7.0 needed?

### ISSUE THREAD

**Issue by Safihre** [taverntesting/tavern#761]
In your `requirements.txt` you block pytest 7.0 and fix it to 6.2.
Is that really needed? I saw in the 2.0 PR you still keep it fixed to 6.2.
I forcefully installed pytest 7.0 and the tavern-tests worked fine, at least in our project.

**Comment by michaelboulton** [comment]
It's not required but I restricted it to <7 in case they changed the API, it looks like this is the only thing and should be easily fixed

```
[#9488](https://github.com/pytest-dev/pytest/issues/9488): If custom subclasses of nodes like [pytest.Item](https://docs.pytest.org/en/7.0.x/reference/reference.html#pytest.Item) override the __init__ method, they should take **kwargs. See [Constructors of custom pytest.Node subclasses should take **kwargs](https://docs.pytest.org/en/7.0.x/deprecations.html#uncooperative-constructors-deprecated) for details.
```
