### ISSUE TITLE
How to get log info

### ISSUE THREAD

**Issue by caibirdme** [taverntesting/tavern#763]
When I run pytest -v，I just get an error report say assertError, but cannot find the log information. Am I missing something?

```py
import logging

def empty_array(response, **kwargs):
    logging.info("get: ", response)
    key = kwargs['key']
    assert len(response.json().get(key)) == 0
```

**Comment by cciotti** [comment]
Create a `pytest.ini` and add this:

```
[pytest]
log_cli = True
log_cli_level = INFO
```

**Comment by michaelboulton** [comment]
In addition to the above, if you want you can also try loading a specific logging config to print out in colours or something if you want, like in Tavern's own tests: https://github.com/taverntesting/tavern/blob/master/tests/conftest.py#L13-L18
