### ISSUE TITLE
What's the proper way to create a shared stage that's a python function that authenticates using boto3 library? (with aws cognito)

### ISSUE THREAD

**Issue by hoIIer** [taverntesting/tavern#782]
My api uses aws cognito and I want to create a test user and then log in before each test (this could be shared so only done once per-pytest run). I would use boto3 to create the user and log in since testing the actual auth mechanisms feels redundant and is covered in browser e2e testing.

How can I achieve this?

**Comment by michaelboulton** [comment]
You probably want to use a shared stage from a configuration file https://tavern.readthedocs.io/en/latest/basics.html#sharing-stages-in-configuration-files

**Comment by hoIIer** [comment]
@michaelboulton versus using the before hook? I guess what would be really nice is a hook that runs once before/after the entire test run vs individual tests

**Comment by michaelboulton** [comment]
If you want to do it before and after each test you can use a [fixture](https://tavern.readthedocs.io/en/latest/basics.html#usefixtures) to log in before and after like
```python
@pytest.fixture(autouse=True)
def create_cognito_session():
    session = log_in()
    
    yield session
    
    log_out(session)
```
You can't run a tavern stage before and after the whole test run like a fixture though

**Comment by hoIIer** [comment]
ok thank!
