### ISSUE TITLE
how can i get coverage after running pytest

### ISSUE THREAD

**Issue by iakirago** [taverntesting/tavern#787]
how can i get coverage after running
`
pytest -v test_01_init_gets.tavern.yaml --html=all.html
`

**Comment by michaelboulton** [comment]
If you mean coverage of your web server code that you are testing, tavern can't do that and you would need to find some way of calculating the coverage on the server side

**Comment by colinshin** [comment]
> If you mean coverage of your web server code that you are testing, tavern can't do that and you would need to find some way of calculating the coverage on the server side

thanks, i know how to do it
