### ISSUE TITLE
BUG: feature-2.0 Older Faker versions using POSIXPath fail with newer python

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [taverntesting/tavern#799]
When attempting to follow the virtual environment setup on the feature-2.0, it failed due to the following reason. 
`AttributeError: 'PosixPath' object has no attribute 'startswith'`

Python Version: `Python 3.10.4`

Faker has a fix for a bug, https://github.com/joke2k/faker/pull/1423

In feature-2.0 branch, the setup.py file says to use `~=5.8.0`
https://github.com/taverntesting/tavern/blob/feature-2.0/setup.py#L6

To get the fix, upgrade faker to `v7.0.1`, or more. I'll create a PR.

**Comment by michaelboulton** [comment]
Fixed in tavern-2.0.0a11
