### ISSUE TITLE
Is there a way to put dynamic content in request json?

### ISSUE THREAD

**Issue by hugogu** [taverntesting/tavern#80]
As far as I see in the docs, it seems all requests json are static content. In some cases, we may want to put something dynamic to cover specific test cases. 

Something like:

>       json: &input_data
>            id: !!python/object:uuid.uuid4

Ideally, it would be great if we can run any python method to populate a value there.

**Comment by benhowes** [comment]
My feeling on this is that either a developer should be using something like the `before`/`after` hooks in #115 to add additional variables which can be templated, or we add the ability to perform an `$ext` method which returns the body to post for more complex cases. What do you think @michaelboulton?

**Comment by michaelboulton** [comment]
Agreed, it should use a hook or a fixture like in #143

**Comment by michaelboulton** [comment]
This was meant to be closed a while ago, shouldn't have left it open so long
