### ISSUE TITLE
Pytest no longer imports py lib

### ISSUE THREAD

**Issue by andrest50** [taverntesting/tavern#816]
I use tavern for API interface testing, and I am getting this error `INTERNALERROR> AttributeError: module 'py' has no attribute 'io'`. Tavern gets the latest version of pytest (<8), and pytest just released 7.2.0, in which it removes dependency on `py`. As per the release (https://github.com/pytest-dev/pytest/releases/tag/7.2.0), you need to now directly install `py` library to make use of the `io` module - as it is still needed in this plugin.

**Comment by IAmSilK** [comment]
Temporary fix for the time being that I have been using - install `py` alongside `tavern` so the package is available.
