### ISSUE TITLE
Please update pinned requirements

### ISSUE THREAD

**Issue by mgorny** [taverntesting/tavern#834]
`tavern` is pinning multiple packages to old versions which prevents systems from upgrading to newer packages. However, it seems that at least some of these pins are outdated/incorrect/unnecessary. After upgrading all of the dependencies, I see the following conflicts caused by tavern:

```
tavern 2.0.0 has requirement jmespath<1, but you have jmespath 1.0.1.
tavern 2.0.0 has requirement jsonschema~=3.2.0, but you have jsonschema 4.17.3.
tavern 2.0.0 has requirement paho-mqtt<=1.5.1,>=1.3.1, but you have paho-mqtt 1.6.1.
tavern 2.0.0 has requirement python-box<6,>=5, but you have python-box 6.1.0.
tavern 2.0.0 has requirement stevedore~=3.3.0, but you have stevedore 4.1.1.
```

However, all tavern's tests seem to pass.

**Comment by michaelboulton** [comment]
Fixed in 2.0.1
