### ISSUE TITLE
Deadlock when executing mqtt-tests

### ISSUE THREAD

**Issue by felixbohnus** [taverntesting/tavern#848]
If you run 

`pytest .\dir\` 

the tests sometimes stops without any further progress.
After a short investigation it seems like tavern runs into a deadlock.
The problem seems to be that the paho-client uses another [thread](https://stackoverflow.com/questions/57925734/does-on-message-in-paho-mqtt-run-in-a-new-thread) for executing the callbacks.

As a result the subscribe_lock of the client.py creates a deadlock

**Comment by michaelboulton** [comment]
I've made a minor modification to the locks in #850 but I can't see anything else that could cause a deadlock. A related question, which version of paho-mqtt are you using? I know some people were having issues with the most recent version, you could try using version 1.5.0 or 1.5.1 and see if that works

**Comment by michaelboulton** [comment]
This should be fixed in 2.0.5, if not then I suspect it's an issue in paho-mqtt
