### ISSUE TITLE
Interactive debug flag

### ISSUE THREAD

**Issue by benhowes** [taverntesting/tavern#87]
Could we have have a flag in a test which would make it really easy to drop in to an `ipdb` environment or something? I'm picturing a situation where we'd be able to:

1. Add a flag to a stage, e.g. `debug: true`
2. When that stage is run it will print out all the block being run, any variables, the result of the test
3. It should print some instructions for defined variables and functions which can be accessed from the debugger
4. It should either instruct that ipdb is needed, or drop in to an ipdb env

This is not a fully formed idea, but I think that we need to focus on the developer experience with tavern more and debugging tests is hard at the moment because the yaml has no breakpoints. Open to suggestions for improvement, but along with better printing of errors in test definitions and better printing of errors when running tests, we should be in a strong position.

**Comment by michaelboulton** [comment]
Now that we have a better error traceback I'm going to close this - don't want to make a whole interactive debug environment
