### ISSUE TITLE
Improve "Saving data with external functions" documentation

### ISSUE THREAD

**Issue by jones77** [taverntesting/tavern#88]
The documentation on "Saving data with external functions" has typos and is confusing.  ie Uses `test_user_name` in the example, but talks about `test_uer_id` [sic].

https://taverntesting.github.io/documentation#saving-data-with-external-functions

~Also, the `<<` notation in the following looks useful but isn't documented.~

Nevermind, I wasn't looking hard enough: https://taverntesting.github.io/documentation#reusing-requests-and-yaml-fragments

https://github.com/taverntesting/tavern/blob/master/example/advanced/test_server.tavern.yaml#L22-L36

**Comment by jones77** [comment]
Note: One thing that wasn't obvious to me was that you can only use saved variables in the same stage.

**Comment by michaelboulton** [comment]
Thanks for noticing this, I've update the documentation to fix the typo and make it clearer that data can only be reused in the same test.
