### ISSUE TITLE
"finally" block errors with BadSchemaError

### ISSUE THREAD

**Issue by sharath-koovill** [taverntesting/tavern#883]
We are running tavern version 2.2.0 which is the latest i believe. The docs from latest:stable shows "finally" block feature available. https://tavern.readthedocs.io/en/latest/basics.html?highlight=finally#finalising-stages

But when i use the finally block, the tests fail with "BadSchemaError". I can see a PR as well https://github.com/taverntesting/tavern/pull/830 which shows its just merged a month back.

Can someone clarify if "finally" block is available in v2.2.0 or yet to be released ?

**Comment by michaelboulton** [comment]
Sorry, this hadn't been released due to an oversight on my part, it should be there in release 2.3.0.
