### ISSUE TITLE
py2.7 unicode problem

### ISSUE THREAD

**Issue by Fosity** [taverntesting/tavern#89]
In the begin project, i set  sys.defalutcoding to utf-8.
The expected body is {'body': {'message': u'\u624b\u673a\u53f7\u683c\u5f0f\u4e0d\u6b63\u786e'}}. they are unicode type.
however, actual body is Response: '<Response [400]>' ({
  "message": "\u624b\u673a\u53f7\u683c\u5f0f\u4e0d\u6b63\u786e"
} . they are str type.
In the error log :
KeyMismatchError: Type of returned data was different than expected (expected = '手机号格式不正确', actual = '手机号格式不正确')
actually, they are the same.
how to do this?
i write 
`        # Normal matching       
        expected_matches = isinstance(expected_val, actual_type)
        if type(expected_val) == type(u''):
            expected_matches = True`
in the util/dict_util.py.

**Comment by michaelboulton** [comment]
Sorry for the late reply, but I think this should be fixed in the latest version due to https://github.com/taverntesting/tavern/pull/72

**Comment by michaelboulton** [comment]
Closing this as it should now be fixed.
