### ISSUE TITLE
Parametrize for request parameters (path, query)

### ISSUE THREAD

**Issue by jykae** [taverntesting/tavern#892]
Seems like parametrize is only supported in request json data
Or is it only I use it somehow improper way

Would it be possible to add parametrize support for request path & query parameters ?

Thank you for creating such great declarative API testing tool @michaelboulton 👏

**Comment by michaelboulton** [comment]
It is possible to parametrize those things, if not documented, I've added an example / test for this in https://github.com/taverntesting/tavern/blob/722b40b786d7933e0243e47996922b45114fdb08/tests/integration/test_parametrize.tavern.yaml#L21-L40
https://github.com/kiril-me/tavern/blob/722b40b786d7933e0243e47996922b45114fdb08/tests/integration/test_parametrize.tavern.yaml#L21-L40 and
