### ISSUE TITLE
DeprecationWarning with jsonschema > 4

### ISSUE THREAD

**Issue by immesys** [taverntesting/tavern#897]
I am getting this error when running my tavern tests:

```
lib/python3.11/site-packages/tavern/_core/schema/jsonschema.py:85: DeprecationWarning: Passing a schema to Validator.is_valid is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).is_valid(...) instead.
```

I used to be able to make this go away by installing jsonschema < 4, but now I have another dependency that requires a higher version of jsonschema.

**Comment by michaelboulton** [comment]
This should be fixed in the latest release
