### ISSUE TITLE
gRPC multi stage test

### ISSUE THREAD

**Issue by AmaniKhalifa** [taverntesting/tavern#915]
Is there a current support for saving a variable from the response of one stage to be used in a next stage for grpc_response.

I see there's a support for http requests using the "save" key.

https://tavern.readthedocs.io/en/latest/examples.html#multi-stage-tests

I think "save" is not expected in the grpc_response keys as I see from here: https://github.com/taverntesting/tavern/blob/da51cd46aa14d6ef76bf5cbf4aba8c946344d783/tavern/_plugins/grpc/response.py#L49C40-L49C47

Is there any other way to do so?

**Comment by michaelboulton** [comment]
There was something missing causing this to fail, I've rectified it in version 2.9.2. This was just beacuse of some old key checking code which needed fixing anyway

**Comment by AmaniKhalifa** [comment]
Thanks @michaelboulton 
seems it's only saved if we verify the same variable we want to save in the body.
While this will work because of checking the body.message:
`    grpc_response:
      status: "OK"
      body:
        message: "Hello, John!"
      save:
        body:
          received_message: message`
so this will fail: 
```
    grpc_response:
      status: "OK"
      save:
        body:
          received_message: message
```

I cannot see any support for arbitrary specific types like anyint, anystr ... etc so does this mean that I need to know the value of the variable in order to save it?

**Comment by michaelboulton** [comment]
That was just an oversight, it should be possible to save values without checking the response values  now in 2.9.3
