### ISSUE TITLE
Example for using $ext

### ISSUE THREAD

**Issue by benhowes** [taverntesting/tavern#94]
It would be useful to be able to show people how to call external functions

**Comment by michaelboulton** [comment]
There's already examples in the examples page (https://taverntesting.github.io/examples) and the documentation (https://taverntesting.github.io/documentation)

**Comment by benhowes** [comment]
The part that's missing is the folder structure and the external functions - i.e. there is no complete example.

**Comment by cjchand** [comment]
I'm happy to help document this, if someone can provide a full directory structured example. 

I'm not a Py dev by trade, but I would have presumed adding a dir relative to either the root of my repo or the dir where the Tavern YAML files would have worked. I was able to open a Py on the command line and import my stuff, so I think it's just something simple I am not groking.

**Comment by michaelboulton** [comment]
I've added a fuller exampled in the 'advanced' example and made the documentation point to it
