### ISSUE TITLE
Option to suppress format variables and error logs on failure

### ISSUE THREAD

**Issue by menma1234** [taverntesting/tavern#943]
We have authorization variables as part of the format variables (the header needs to be constructed via code) and this gets sent as part of the request.

When a test fails for whatever reason, all of the available format variables as well as the values formatted into the request will get dumped into logs, which isn't great considering these auth headers can be considered sensitive. If there were an option to suppress these from being logged (or at least being able to configure which variables and headers shouldn't get logged) that'd be great.

**Comment by michaelboulton** [comment]
There could be an option in Tavern to never print any format variables but frankly I'm sure that there would be a _lot_ of times when I accidentally missed this somehow and the secret would end up in the logs anyway, and a security feature that only works _most_ of the time isn't really secure at all.
It would also be annoying to have _every_ format variable masked (including things like base URLs) if you're trying to debug something, and it would be a pretty big and invasive code change to track individual format variables which are considered 'secret' throughout the whole codebase.
Pretty much any CI system should already mask any 'secret' variables you have, for example if you print a 'secret' in github actions it will show it as ***** in the logs instead - this is the behaviour that should be relied on more than anything else, I don't think this will get implemented in Tavern, sorry!
